### ISSUE TITLE
Phoenicis on TrueOS

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/phoenicis#1217]
I managed to build phoenicis in TrueOs by creating a "FreeBSD.properties" like this one : 

```
pplication.name                            =           Phoenicis PlayOnBSD

application.user.root                       =           ${user.home}/.Phoenicis
application.user.desktopShortcuts           =           ${user.home}/.local/share/applications
application.user.tmp                        =           ${application.user.root}/tmp
application.user.containers                 =           ${application.user.root}/containers/
application.user.shortcuts                  =           ${application.user.root}/shortcuts/
application.user.logs                       =           ${application.user.root}/logs
application.user.engines                    =           ${application.user.root}/engines/
application.user.resources                  =           ${application.user.root}/resources/
application.user.settings                   =           ${application.user.root}/config.properties
application.user.repository                 =           ${application.user.root}/repository/
application.user.cache                      =           ${application.user.root}/cache/

application.repository.list                 =           ${application.user.root}/repositories.json

application.root                            =           ${user.dir}
application.macosx.tools                    =
application.environment.path                =
application.environment.ld                  =
application.environment.dyld                =

webservice.wine.url                         =           http://phoenicis.playonlinux.com/index.php/wine?os=linux
```
Even if I know the website wine url is not the right one.

However, I got an error saying that "substring" does not exist in Downloader.

And there is no text btw, only rectangle.

Any idea ? :-)
![bsd](https://user-images.githubusercontent.com/19779882/38176987-6ac0544e-35f9-11e8-81cf-d81ed6d187c5.png)

**Comment by plata** [comment]
Can you show the error message for the Downloader error?

**Comment by plata** [comment]
For the text: seems like the font is not available. To verify please remove
```CSS
-fx-text-font-family: "Roboto Light";
```
from `org/phoenicis/javafx/themes/default/main.less` (you must build afterwards).

**Comment by ImperatorS79** [comment]
When removing this, I do not see any changes.

Here is the log : 
 ```
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.63) - java.lang.IllegalStateException: javax.script.ScriptException: TypeError: null has no such function "substring" in [Utils, Functions, Net, Download] at line number 11
        at org.phoenicis.engines.EnginesSource.throwError(EnginesSource.java:95)
        at org.phoenicis.scripts.nashorn.NashornEngine.handleError(NashornEngine.java:74)
        at org.phoenicis.scripts.nashorn.NashornEngine.evalAndReturn(NashornEngine.java:65)
        at org.phoenicis.scripts.nashorn.NashornInteractiveSession.eval(NashornInteractiveSession.java:34)
        at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$null$1(BackgroundScriptInterpreter.java:43)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.script.ScriptException: TypeError: null has no such function "substring" in [Utils, Functions, Net, Download] at line number 11
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:454)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
        at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
        at org.phoenicis.scripts.nashorn.NashornEngine.evalAndReturn(NashornEngine.java:59)
        ... 5 more
Caused by: [Utils, Functions, Net, Download]:11 TypeError: null has no such function "substring"
        at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
        at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.linkNull(NashornBottomLinker.java:180)
        at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.getGuardedInvocation(NashornBottomLinker.java:66)
        at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
        at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
        at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
        at jdk.nashorn.internal.scripts.Script$Recompilation$21$304A$\^eval\_.Downloader#_fetchFileNameFromUrl([Utils, Functions, Net, Download]:11)
        at jdk.nashorn.internal.scripts.Script$Recompilation$20$1150$\^eval\_.Downloader#get([Utils, Functions, Net, Download]:43)
        at jdk.nashorn.internal.scripts.Script$Recompilation$12$8372$\^eval\_.getAvailableVersions([Engines, Wine, Engine, Object]:332)
        at jdk.nashorn.internal.scripts.Script$Recompilation$10$24$\^eval\_.fetchEngines(<eval>:3)
        at jdk.nashorn.internal.scripts.Script$9$\^eval\_.:program(<eval>:6)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
        ... 10 more

Exception in thread "pool-3-thread-2" java.lang.IllegalStateException: javax.script.ScriptException: TypeError: null has no such function "substring" in [Utils, Functions, Net, Download] at line number 11
        at org.phoenicis.engines.EnginesSource.throwError(EnginesSource.java:95)
        at org.phoenicis.scripts.nashorn.NashornEngine.handleError(NashornEngine.java:74)
        at org.phoenicis.scripts.nashorn.NashornEngine.evalAndReturn(NashornEngine.java:65)
        at org.phoenicis.scripts.nashorn.NashornInteractiveSession.eval(NashornInteractiveSession.java:34)
        at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$null$1(BackgroundScriptInterpreter.java:43)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.script.ScriptException: TypeError: null has no such function "substring" in [Utils, Functions, Net, Download] at line number 11
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:454)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
        at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
        at org.phoenicis.scripts.nashorn.NashornEngine.evalAndReturn(NashornEngine.java:59)
        ... 5 more
Caused by: [Utils, Functions, Net, Download]:11 TypeError: null has no such function "substring"
        at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
        at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.linkNull(NashornBottomLinker.java:180)
        at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.getGuardedInvocation(NashornBottomLinker.java:66)
        at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
        at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
        at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
        at jdk.nashorn.internal.scripts.Script$Recompilation$21$304A$\^eval\_.Downloader#_fetchFileNameFromUrl([Utils, Functions, Net, Download]:11)
        at jdk.nashorn.internal.scripts.Script$Recompilation$20$1150$\^eval\_.Downloader#get([Utils, Functions, Net, Download]:43)
        at jdk.nashorn.internal.scripts.Script$Recompilation$12$8372$\^eval\_.getAvailableVersions([Engines, Wine, Engine, Object]:332)
        at jdk.nashorn.internal.scripts.Script$Recompilation$10$24$\^eval\_.fetchEngines(<eval>:3)
        at jdk.nashorn.internal.scripts.Script$9$\^eval\_.:program(<eval>:6)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
        ... 10 more
```

**Comment by ImperatorS79** [comment]
I have installed google fonts, and now I have this ^^
![screenshot_20180404_235919](https://user-images.githubusercontent.com/19779882/38337118-6bc7abfe-3864-11e8-8caf-2680fc0122e5.png)

**Comment by ImperatorS79** [comment]
For an unknown reason, no more errors !
![pobsd](https://user-images.githubusercontent.com/19779882/38491867-6c95e8e8-3bed-11e8-98bd-bec64e8191e0.png)

For the fonts, I have downloaded Roboto-Regular.ttf and Roboto-Light.ttf, placed them in the same directory as main.less, and add : 
```
@font-face {
    src: url("Roboto-Regular.ttf");
}
```
in main.less and

```
@font-face {
    src: url("Roboto-Light.ttf");
}
```

in description.less and I got this : 

![font](https://user-images.githubusercontent.com/19779882/38493167-7f952d2e-3bf1-11e8-8edf-d8e92313e07e.png)

**Comment by plata** [comment]
This font issue is really weird. Maybe ask in a TrueOS forum?

**Comment by ImperatorS79** [comment]
Ok, just removed google-fonts and installed robot-fonts-ttf, got this ->
![pbsd works](https://user-images.githubusercontent.com/19779882/39092673-69d09024-4613-11e8-973c-604034def764.png)

The last tthing is to provide wine builds for FreeBSD, and it will be working.

**Comment by plata** [comment]
Can you provide a description for the docs with the required steps?

**Comment by ImperatorS79** [comment]
About how to buid it ?

**Comment by plata** [comment]
Yes, and all the things you had to do to make it run properly.

**Comment by unwillexist** [comment]
How did you manage to build in FreeBSD without javafx ?

**Comment by ImperatorS79** [comment]
At that time the project used openjdk-8 and there was a openjfx-8 package on TrueOS.

Note that TrueOS is not a desktop freeBSD distro anymore.
