### ISSUE TITLE
buildNumber missing when building downloaded .zip

### ISSUE THREAD

**Issue by atilling** [PhoenicisOrg/phoenicis#1340]
OSX 10.13.4
Java 1.8.0_144
Maven 3.5.3

Error on Mvn Cln package

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.864 s <<< FAILURE! - in org.phoenicis.javafx.AppConfigurationInitialisationTest
testAppConfigurationInitialisation(org.phoenicis.javafx.AppConfigurationInitialisationTest)  Time elapsed: 0.83 s  <<< ERROR!
java.lang.RuntimeException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.phoenicis.javafx.controller.ControllerConfiguration': Unsatisfied dependency expressed through field 'viewsConfiguration'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.phoenicis.javafx.views.ViewsConfiguration': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'buildNumber' in value "${buildNumber}"
	at org.phoenicis.javafx.AppConfigurationInitialisationTest.testAppConfigurationInitialisation(AppConfigurationInitialisationTest.java:22)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.phoenicis.javafx.controller.ControllerConfiguration': Unsatisfied dependency expressed through field 'viewsConfiguration'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.phoenicis.javafx.views.ViewsConfiguration': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'buildNumber' in value "${buildNumber}"
	at org.phoenicis.javafx.AppConfigurationInitialisationTest.lambda$testAppConfigurationInitialisation$0(AppConfigurationInitialisationTest.java:22)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.phoenicis.javafx.views.ViewsConfiguration': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'buildNumber' in value "${buildNumber}"
	at org.phoenicis.javafx.AppConfigurationInitialisationTest.lambda$testAppConfigurationInitialisation$0(AppConfigurationInitialisationTest.java:22)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'buildNumber' in value "${buildNumber}"
	at org.phoenicis.javafx.AppConfigurationInitialisationTest.lambda$testAppConfigurationInitialisation$0(AppConfigurationInitialisationTest.java:22)

[Build_output.txt](https://github.com/PhoenicisOrg/phoenicis/files/2032909/Build_output.txt)

**Comment by atilling** [comment]
Note error was in master branch but I get the same error in the 5.0 alpha branch.

**Comment by plata** [comment]
Did you checkout or just download the .zip with the sources?

**Comment by atilling** [comment]
Downloaded zip with sources - I can do a checkout if that would have missed something.

**Comment by plata** [comment]
Yes, try it please. If it works, we must fix the build for the downloaded zip.

**Comment by atilling** [comment]
Did a clone, and mvn clean package within the clone repo and I was able to build. Though my eclipse doesn't like gettext plugin - I'll have to check why.

**Comment by plata** [comment]
Might be that you have to install gettext. Not sure if you can do that directly, otherwise use homebrew.
