### ISSUE TITLE
Folder '/home/user/.Phoenicis/cache/git-331995911' is no git-repository

### ISSUE THREAD

**Issue by infinitnet** [PhoenicisOrg/phoenicis#1347]
Getting this right after launch. Clean reinstall didn't help. Using this AUR package: https://aur.archlinux.org/packages/playonlinux5-git/

```
[DEBUG] org.springframework.context.annotation.AnnotationConfigApplicationContext (l.792) - Unable to locate LifecycleProcessor with name 'lifecycleProcessor': using default [org.springframework.context.support.DefaultLifecycleProcessor@645aa0df]
[DEBUG] org.springframework.beans.factory.support.DefaultListableBeanFactory (l.254) - Returning cached instance of singleton bean 'lifecycleProcessor'
[DEBUG] org.springframework.core.env.PropertySourcesPropertyResolver (l.96) - Could not find key 'spring.liveBeansView.mbeanDomain' in any property source
[DEBUG] org.springframework.beans.factory.support.DefaultListableBeanFactory (l.254) - Returning cached instance of singleton bean 'mainController'
[ERROR] org.phoenicis.repository.types.Repository (l.51) - Fetching installable applications failed!
org.phoenicis.repository.RepositoryException: Folder '/home/user/.Phoenicis/cache/git-331995911' is no git-repository
        at org.phoenicis.repository.types.GitRepository.fetchInstallableApplications(GitRepository.java:114)
        at java.util.stream.Collectors.lambda$toConcurrentMap$59(Collectors.java:1473)
        at java.util.stream.ReferencePipeline.lambda$collect$1(ReferencePipeline.java:496)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /home/user/.Phoenicis/cache/git-331995911
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:614)
        at org.eclipse.jgit.api.Git.open(Git.java:122)
        at org.eclipse.jgit.api.Git.open(Git.java:102)
        at org.phoenicis.repository.types.GitRepository.fetchInstallableApplications(GitRepository.java:103)
        ... 11 common frames omitted
```

```
$ java -version
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
openjdk version "1.8.0_172"
OpenJDK Runtime Environment (build 1.8.0_172-b11)
OpenJDK 64-Bit Server VM (build 25.172-b11, mixed mode)
```

**Comment by ImperatorS79** [comment]
Could you try to delete that directory before relanching the app ?

**Comment by infinitnet** [comment]
That did the trick.
