### ISSUE TITLE
Unable to Lauch phoenicis

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/phoenicis#1418]
### Expected behavior
Launch the app
### Actual behavior
```
[WARN ] org.springframework.context.annotation.AnnotationConfigApplicationContext (l.556) - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mainController' defined in org.phoenicis.javafx.controller.ControllerConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.phoenicis.javafx.controller.MainController]: Factory method 'mainController' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'libraryController' defined in org.phoenicis.javafx.controller.ControllerConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.phoenicis.javafx.controller.library.LibraryController]: Factory method 'libraryController' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'viewLibrary' defined in org.phoenicis.javafx.views.ViewsConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.phoenicis.javafx.views.mainwindow.library.LibraryView]: Factory method 'viewLibrary' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'javaFxSettingsManager': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'application.theme' in value "${application.theme}"
Exception in Application start method
java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mainController' defined in org.phoenicis.javafx.controller.ControllerConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.phoenicis.javafx.controller.MainController]: Factory method 'mainController' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'libraryController' defined in org.phoenicis.javafx.controller.ControllerConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.phoenicis.javafx.controller.library.LibraryController]: Factory method 'libraryController' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'viewLibrary' defined in org.phoenicis.javafx.views.ViewsConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.phoenicis.javafx.views.mainwindow.library.LibraryView]: Factory method 'viewLibrary' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'javaFxSettingsManager': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'application.theme' in value "${application.theme}"
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:625)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1287)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1126)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:848)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:865)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:548)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:88)
	at org.phoenicis.javafx.JavaFXApplication.start(JavaFXApplication.java:45)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
	... 1 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.phoenicis.javafx.controller.MainController]: Factory method 'mainController' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'libraryController' defined in org.phoenicis.javafx.controller.ControllerConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.phoenicis.javafx.controller.library.LibraryController]: Factory method 'libraryController' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'viewLibrary' defined in org.phoenicis.javafx.views.ViewsConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.phoenicis.javafx.views.mainwindow.library.LibraryView]: Factory method 'viewLibrary' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'javaFxSettingsManager': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'application.theme' in value "${application.theme}"
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:620)
	... 23 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'libraryController' defined in org.phoenicis.javafx.controller.ControllerConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.phoenicis.javafx.controller.library.LibraryController]: Factory method 'libraryController' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'viewLibrary' defined in org.phoenicis.javafx.views.ViewsConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.phoenicis.javafx.views.mainwindow.library.LibraryView]: Factory method 'viewLibrary' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'javaFxSettingsManager': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'application.theme' in value "${application.theme}"
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:625)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1287)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1126)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:394)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:366)
	at org.phoenicis.javafx.controller.ControllerConfiguration$$EnhancerBySpringCGLIB$$cbbe27d4.libraryController(<generated>)
	at org.phoenicis.javafx.controller.ControllerConfiguration.mainController(ControllerConfiguration.java:74)
	at org.phoenicis.javafx.controller.ControllerConfiguration$$EnhancerBySpringCGLIB$$cbbe27d4.CGLIB$mainController$7(<generated>)
	at org.phoenicis.javafx.controller.ControllerConfiguration$$EnhancerBySpringCGLIB$$cbbe27d4$$FastClassBySpringCGLIB$$c8bcea82.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at org.phoenicis.javafx.controller.ControllerConfiguration$$EnhancerBySpringCGLIB$$cbbe27d4.mainController(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 24 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.phoenicis.javafx.controller.library.LibraryController]: Factory method 'libraryController' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'viewLibrary' defined in org.phoenicis.javafx.views.ViewsConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.phoenicis.javafx.views.mainwindow.library.LibraryView]: Factory method 'viewLibrary' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'javaFxSettingsManager': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'application.theme' in value "${application.theme}"
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:620)
	... 47 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'viewLibrary' defined in org.phoenicis.javafx.views.ViewsConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.phoenicis.javafx.views.mainwindow.library.LibraryView]: Factory method 'viewLibrary' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'javaFxSettingsManager': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'application.theme' in value "${application.theme}"
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:625)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1287)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1126)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:394)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:366)
	at org.phoenicis.javafx.views.ViewsConfiguration$$EnhancerBySpringCGLIB$$52feb9d4.viewLibrary(<generated>)
	at org.phoenicis.javafx.controller.ControllerConfiguration.libraryController(ControllerConfiguration.java:104)
	at org.phoenicis.javafx.controller.ControllerConfiguration$$EnhancerBySpringCGLIB$$cbbe27d4.CGLIB$libraryController$3(<generated>)
	at org.phoenicis.javafx.controller.ControllerConfiguration$$EnhancerBySpringCGLIB$$cbbe27d4$$FastClassBySpringCGLIB$$c8bcea82.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at org.phoenicis.javafx.controller.ControllerConfiguration$$EnhancerBySpringCGLIB$$cbbe27d4.libraryController(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 48 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.phoenicis.javafx.views.mainwindow.library.LibraryView]: Factory method 'viewLibrary' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'javaFxSettingsManager': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'application.theme' in value "${application.theme}"
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:620)
	... 71 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'javaFxSettingsManager': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'application.theme' in value "${application.theme}"
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:382)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1377)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:575)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:394)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:366)
	at org.phoenicis.javafx.settings.JavaFxSettingsConfiguration$$EnhancerBySpringCGLIB$$3fdccd80.javaFxSettingsManager(<generated>)
	at org.phoenicis.javafx.views.mainwindow.library.ViewsConfigurationLibrary.viewLibrary(ViewsConfigurationLibrary.java:53)
	at org.phoenicis.javafx.views.mainwindow.library.ViewsConfigurationLibrary$$EnhancerBySpringCGLIB$$dc70f987.CGLIB$viewLibrary$0(<generated>)
	at org.phoenicis.javafx.views.mainwindow.library.ViewsConfigurationLibrary$$EnhancerBySpringCGLIB$$dc70f987$$FastClassBySpringCGLIB$$272dfc2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at org.phoenicis.javafx.views.mainwindow.library.ViewsConfigurationLibrary$$EnhancerBySpringCGLIB$$dc70f987.viewLibrary(<generated>)
	at org.phoenicis.javafx.views.ViewsConfiguration.viewLibrary(ViewsConfiguration.java:114)
	at org.phoenicis.javafx.views.ViewsConfiguration$$EnhancerBySpringCGLIB$$52feb9d4.CGLIB$viewLibrary$0(<generated>)
	at org.phoenicis.javafx.views.ViewsConfiguration$$EnhancerBySpringCGLIB$$52feb9d4$$FastClassBySpringCGLIB$$37d6e80e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at org.phoenicis.javafx.views.ViewsConfiguration$$EnhancerBySpringCGLIB$$52feb9d4.viewLibrary(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 72 more
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'application.theme' in value "${application.theme}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:172)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124)
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:237)
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:211)
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:175)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:842)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1189)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1168)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:595)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:376)
	... 99 more
```
### System information
* Latest
* Ubuntu 18.04
* openjdk 8

**Comment by madoar** [comment]
This looks like a problem with the created `javafx.properties` file.
Can you tell us the content of your `~/.Phoenicis/javafx.properties` file?

**Comment by ImperatorS79** [comment]
There is not that file in that directory.

**Comment by madoar** [comment]
Can you please delete the whole `~/.Phoenicis` folder and restart the application and tell us if this fixes the issue?

**Comment by ImperatorS79** [comment]
Same error.

**Comment by madoar** [comment]
How did you start/install Phoenicis?
Can you tell us the content of your `~/.Phoenicis` folder?

**Comment by ImperatorS79** [comment]
I compiled phoenicis following the wiki. I started it with ./phoenicis.sh. There is only a phoenicis.log in that folder.

**Comment by madoar** [comment]
I can reproduce the issue.

At the moment I can't say where the issue is located.
I've discovered, that the problem occurs during the creation of the singleton bean `javaFxSettingsManager` at https://github.com/PhoenicisOrg/phoenicis/blob/master/phoenicis-javafx/src/main/java/org/phoenicis/javafx/settings/JavaFxSettingsConfiguration.java#L36.
The other property files don't seem to create any problems, at least for me.

**Comment by madoar** [comment]
Interesting, if you manually copy the `javafx.properties` file to `~/.Phoenicis` the application starts.
This means, that the application has a problem with locating the file on the classpath.

@plata maybe the issue has been introduced by a `spring` dependency version update?

**Comment by plata** [comment]
Just tried from my IDE and didn't have any issues. Also, I think that the `AppConfigurationInitialisationTest` should fail if we have an issue with spring.

Btw: the run description in the documentation seems to be wrong. Can anyone of you fix it with the commands you're using?

**Comment by plata** [comment]
I can reproduce the issue with:
```
/usr/lib/jvm/java-8-openjdk-amd64/bin/java -cp "./lib/*" org.phoenicis.javafx.JavaFXApplication
```
Do not understand why it's different in the IDE.

**Comment by madoar** [comment]
Just as a side note:
I've reproduced the problem with the `deb` installer.

**Comment by plata** [comment]
Flatpak as well.

**Comment by plata** [comment]
Downgraded to spring framework 5.0.9 but no difference.

It must be somehow related to the classpath/jar where the javafx.properties is located: I copied it to phoenicis-configuration/resources and that's working.
