### ISSUE TITLE
Cannot create container with custom installer

### ISSUE THREAD

**Issue by t0msk** [PhoenicisOrg/phoenicis#1438]
### Expected behavior
It should create container.

### Actual behavior
If I select Local installer in Apps tab and lick on Install button then I get this error:
```
org.phoenicis.scripts.interpreter.ScriptException: org.phoenicis.scripts.interpreter.ScriptException: org.phoenicis.scripts.interpreter.ScriptException: org.phoenicis.scripts.interpreter.ScriptException: org.phoenicis.scripts.interpreter.ScriptException: org.phoenicis.scripts.interpreter.ScriptException: javax.script.ScriptException: TypeError: Java.extend needs Java types as its arguments. in [engines, wine, engine, implementation] at line number 288
	at org.phoenicis.scripts.nashorn.builtins.EngineInjector.throwException(EngineInjector.java:22)
	at org.phoenicis.scripts.nashorn.NashornEngine.handleError(NashornEngine.java:74)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:53)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:44)
	at org.phoenicis.scripts.nashorn.builtins.IncludeInjector.lambda$injectInto$0(IncludeInjector.java:36)
	at jdk.nashorn.internal.scripts.Script$41$\^eval\_.:program(<eval>:5)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.phoenicis.scripts.interpreter.ScriptException: org.phoenicis.scripts.interpreter.ScriptException: org.phoenicis.scripts.interpreter.ScriptException: org.phoenicis.scripts.interpreter.ScriptException: org.phoenicis.scripts.interpreter.ScriptException: javax.script.ScriptException: TypeError: Java.extend needs Java types as its arguments. in [engines, wine, engine, implementation] at line number 288
	at org.phoenicis.scripts.nashorn.builtins.EngineInjector.throwException(EngineInjector.java:22)
	at org.phoenicis.scripts.nashorn.NashornEngine.handleError(NashornEngine.java:74)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:53)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:44)
	at org.phoenicis.scripts.nashorn.builtins.IncludeInjector.lambda$injectInto$0(IncludeInjector.java:36)
	at jdk.nashorn.internal.scripts.Script$42$\^eval\_.:program([engines, wine, quick_script, local_installer_script]:2)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	... 17 more
Caused by: org.phoenicis.scripts.interpreter.ScriptException: org.phoenicis.scripts.interpreter.ScriptException: org.phoenicis.scripts.interpreter.ScriptException: org.phoenicis.scripts.interpreter.ScriptException: javax.script.ScriptException: TypeError: Java.extend needs Java types as its arguments. in [engines, wine, engine, implementation] at line number 288
	at org.phoenicis.scripts.nashorn.builtins.EngineInjector.throwException(EngineInjector.java:22)
	at org.phoenicis.scripts.nashorn.NashornEngine.handleError(NashornEngine.java:74)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:53)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:44)
	at org.phoenicis.scripts.nashorn.builtins.IncludeInjector.lambda$injectInto$0(IncludeInjector.java:36)
	at jdk.nashorn.internal.scripts.Script$43$\^eval\_.:scopeCall([engines, wine, quick_script, installer_script])
	at jdk.nashorn.internal.scripts.Script$43$\^eval\_.:program([engines, wine, quick_script, installer_script]:2)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	... 29 more
Caused by: org.phoenicis.scripts.interpreter.ScriptException: org.phoenicis.scripts.interpreter.ScriptException: org.phoenicis.scripts.interpreter.ScriptException: javax.script.ScriptException: TypeError: Java.extend needs Java types as its arguments. in [engines, wine, engine, implementation] at line number 288
	at org.phoenicis.scripts.nashorn.builtins.EngineInjector.throwException(EngineInjector.java:22)
	at org.phoenicis.scripts.nashorn.NashornEngine.handleError(NashornEngine.java:74)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:53)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:44)
	at org.phoenicis.scripts.nashorn.builtins.IncludeInjector.lambda$injectInto$0(IncludeInjector.java:36)
	at jdk.nashorn.internal.scripts.Script$44$\^eval\_.:program([engines, wine, quick_script, quick_script]:2)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	... 42 more
Caused by: org.phoenicis.scripts.interpreter.ScriptException: org.phoenicis.scripts.interpreter.ScriptException: javax.script.ScriptException: TypeError: Java.extend needs Java types as its arguments. in [engines, wine, engine, implementation] at line number 288
	at org.phoenicis.scripts.nashorn.builtins.EngineInjector.throwException(EngineInjector.java:22)
	at org.phoenicis.scripts.nashorn.NashornEngine.handleError(NashornEngine.java:74)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:53)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:44)
	at org.phoenicis.scripts.nashorn.builtins.IncludeInjector.lambda$injectInto$0(IncludeInjector.java:36)
	at jdk.nashorn.internal.scripts.Script$45$\^eval\_.:program([engines, wine, shortcuts, wine]:2)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	... 54 more
Caused by: org.phoenicis.scripts.interpreter.ScriptException: javax.script.ScriptException: TypeError: Java.extend needs Java types as its arguments. in [engines, wine, engine, implementation] at line number 288
	at org.phoenicis.scripts.nashorn.builtins.EngineInjector.throwException(EngineInjector.java:22)
	at org.phoenicis.scripts.nashorn.NashornEngine.handleError(NashornEngine.java:74)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:53)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:44)
	at org.phoenicis.scripts.nashorn.builtins.IncludeInjector.lambda$injectInto$0(IncludeInjector.java:36)
	at jdk.nashorn.internal.scripts.Script$46$\^eval\_.:scopeCall([engines, wine, engine, object])
	at jdk.nashorn.internal.scripts.Script$46$\^eval\_.:program([engines, wine, engine, object]:2)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	... 66 more
Caused by: javax.script.ScriptException: TypeError: Java.extend needs Java types as its arguments. in [engines, wine, engine, implementation] at line number 288
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:454)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	... 79 more
Caused by: [engines, wine, engine, implementation]:288 TypeError: Java.extend needs Java types as its arguments.
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.nashorn.internal.objects.NativeJava.extend(NativeJava.java:630)
	at jdk.nashorn.internal.scripts.Script$47$\^eval\_.:program([engines, wine, engine, implementation]:288)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	... 84 more
```

### Steps to reproduce
Open Apps, select Local installer, click on Install.

### System information
* used operating system: KDE Neon 18.04
* used Java version: openjdk version "1.8.0_181"

**Comment by plata** [comment]
Other app installations are working?

**Comment by t0msk** [comment]
Yes

**Comment by plata** [comment]
Please ensure that you use the current master for the software and the scripts.

**Comment by t0msk** [comment]
How? I just followed steps in readme.md.

**Comment by plata** [comment]
Have a look at https://phoenicisorg.github.io/phoenicis/Users/repository/#git. If you cloned the repository, this should be the default though.

**Comment by plata** [comment]
Looks like your repository has not been up to date before. Can you install apps now? If so, everything should be fine.

**Comment by t0msk** [comment]
@plata as I said when I created `.repositories.json` inside `.Phoenicis` folder (it wasn't filled) with this data:
```
{
   "type":"git",
   "gitRepositoryUri":"https://github.com/PhoenicisOrg/scripts",
   "branch":"master"
}
```
I still have that error + now I lost **Wine Tools** panel in ### Containers.

**Comment by t0msk** [comment]
Can someone help me, please?

**Comment by t0msk** [comment]
And again do this:
Build
`mvn clean package`

Run
```
cd phoenicis-dist/target
unzip phoenicis-dist.zip
./phoenicis-dist/phoenicis.sh
```
?

**Comment by plata** [comment]
Yes.

**Comment by t0msk** [comment]
Okey, looks like it is fixed, errors are gone, but during installation of Battle.NET app I get an error "Cannot launch the Blizzard App. A required DLL could not be found. Please download and reinstall the Blizzard app." and it refers to https://us.battle.net/support/en/article/135608, but I cannot install these packages because there is not support for Verbs yet.

**Comment by plata** [comment]
Feel free to open an issue regarding Battle.NET in the scripts repository.
