### ISSUE TITLE
How to run winetricks command inside container

### ISSUE THREAD

**Issue by t0msk** [PhoenicisOrg/phoenicis#1527]
Hello, I just have to run this command `winetricks settings fontsmooth=rgb` inside my container, how can I do it?

**Comment by plata** [comment]
You should consider to implement a Wine setting for this. See https://github.com/PhoenicisOrg/scripts/tree/master/Engines/Wine/Settings

**Comment by t0msk** [comment]
Why? Imagine that I have to run another winetricks commands, not only `winetricks settings fontsmooth=rgb`, so I just wonder how can I run some commands for that container.

**Comment by plata** [comment]
Well, you can always go to your shell and run it from there. I just tried to provide an answer which would integrate nicely with Phoenicis.

**Comment by t0msk** [comment]
Ah yes, ok so I can add it if I understand how. But how can I run winetricks command that will modify Phoenicis container and not System-wide wine?

**Comment by plata** [comment]
Use "Open terminal" in Container → your container → Engine Tools.

**Comment by t0msk** [comment]
It doesn't work, I clicked on "Open terminal" as you can see on the screenshot, but nothing happened, it just grayed out.
![screenshot_20181203_192646](https://user-images.githubusercontent.com/7276200/49393577-ead3b000-f731-11e8-8c71-36368d8b764a.png)

**Comment by plata** [comment]
Anything in the logs?

**Comment by t0msk** [comment]
```
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.63) - [engines, wine, tools, wine_terminal_opener]:15 TypeError: this._TerminalOpener.openTerminal is not a function
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Undefined.lookup(Undefined.java:100)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:106)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:96)
        at jdk.dynalink/jdk.dynalink.linker.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:184)
        at jdk.dynalink/jdk.dynalink.linker.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:132)
        at jdk.dynalink/jdk.dynalink.LinkerServicesImpl.lambda$getGuardedInvocation$0(LinkerServicesImpl.java:160)
        at jdk.dynalink/jdk.dynalink.LinkerServicesImpl.getWithLookupInternal(LinkerServicesImpl.java:191)
        at jdk.dynalink/jdk.dynalink.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:158)
        at jdk.dynalink/jdk.dynalink.DynamicLinker.relink(DynamicLinker.java:265)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$306$243A$\^eval\_$cu1$restOf.run([engines, wine, tools, wine_terminal_opener]:15)
        at jdk.nashorn.javaadapters.org_phoenicis_engines_EngineTool.run(Unknown Source)
        at org.phoenicis.engines/org.phoenicis.engines.EngineToolsManager.lambda$runTool$0(EngineToolsManager.java:64)
        at org.phoenicis.scripts/org.phoenicis.scripts.nashorn.NashornInteractiveSession.eval(NashornInteractiveSession.java:34)
        at org.phoenicis.scripts/org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:43)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)

Exception in thread "pool-3-thread-5" [engines, wine, tools, wine_terminal_opener]:15 TypeError: this._TerminalOpener.openTerminal is not a function
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Undefined.lookup(Undefined.java:100)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:106)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:96)
        at jdk.dynalink/jdk.dynalink.linker.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:184)
        at jdk.dynalink/jdk.dynalink.linker.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:132)
        at jdk.dynalink/jdk.dynalink.LinkerServicesImpl.lambda$getGuardedInvocation$0(LinkerServicesImpl.java:160)
        at jdk.dynalink/jdk.dynalink.LinkerServicesImpl.getWithLookupInternal(LinkerServicesImpl.java:191)
        at jdk.dynalink/jdk.dynalink.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:158)
        at jdk.dynalink/jdk.dynalink.DynamicLinker.relink(DynamicLinker.java:265)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$306$243A$\^eval\_$cu1$restOf.run([engines, wine, tools, wine_terminal_opener]:15)
        at jdk.nashorn.javaadapters.org_phoenicis_engines_EngineTool.run(Unknown Source)
        at org.phoenicis.engines/org.phoenicis.engines.EngineToolsManager.lambda$runTool$0(EngineToolsManager.java:64)
        at org.phoenicis.scripts/org.phoenicis.scripts.nashorn.NashornInteractiveSession.eval(NashornInteractiveSession.java:34)
        at org.phoenicis.scripts/org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:43)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by plata** [comment]
You're using Java 10/11 right?

**Comment by t0msk** [comment]
Yes
```
tomsk@tomsk-pc:~$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
```
