### ISSUE TITLE
Cannot close engine details view

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1589]
### Expected behavior
Engines → details view closes when clicking "X"

### Actual behavior
It doesn't.

### Steps to reproduce
- click engine
- install engine (not sure if this is required)
- try to close details view

### System information
* current master, Ubuntu 18.04.1 with OpenJDK 11

**Comment by madoar** [comment]
Do you get any error message?

**Comment by plata** [comment]
I didn't check. Just running through the test plan. Also, it seems that you can normally close the details view. So it must be happening only in a special situation (if an installation is running or something like that).

**Comment by madoar** [comment]
Ok, I didn't have the same visual effect but my terminal now contains the following error message:

```
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.63) - java.lang.IllegalStateException: Not on FX application thread; currentThread = pool-3-thread-5
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.Parent$2.onProposedChange(Parent.java:367)
	at com.sun.javafx.collections.VetoableListDecorator.remove(VetoableListDecorator.java:329)
	at com.sun.javafx.collections.VetoableListDecorator.remove(VetoableListDecorator.java:221)
	at javafx.scene.layout.BorderPane$BorderPositionProperty.invalidated(BorderPane.java:673)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:111)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.layout.BorderPane.setCenter(BorderPane.java:260)
	at org.phoenicis.javafx.views.mainwindow.ui.MainWindowView.setCenter(MainWindowView.java:99)
	at org.phoenicis.javafx.views.mainwindow.ui.MainWindowView.showWait(MainWindowView.java:122)
	at org.phoenicis.javafx.controller.engines.EnginesController.populateView(EnginesController.java:136)
	at org.phoenicis.javafx.controller.engines.EnginesController.forceViewUpdate(EnginesController.java:206)
	at org.phoenicis.javafx.controller.engines.EnginesController.lambda$null$10(EnginesController.java:103)
	at org.phoenicis.engines.EnginesManager.lambda$getEngine$0(EnginesManager.java:71)
	at org.phoenicis.scripts.nashorn.NashornInteractiveSession.eval(NashornInteractiveSession.java:34)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$null$1(BackgroundScriptInterpreter.java:43)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Exception in thread "pool-3-thread-5" java.lang.IllegalStateException: Not on FX application thread; currentThread = pool-3-thread-5
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.Parent$2.onProposedChange(Parent.java:367)
	at com.sun.javafx.collections.VetoableListDecorator.remove(VetoableListDecorator.java:329)
	at com.sun.javafx.collections.VetoableListDecorator.remove(VetoableListDecorator.java:221)
	at javafx.scene.layout.BorderPane$BorderPositionProperty.invalidated(BorderPane.java:673)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:111)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.layout.BorderPane.setCenter(BorderPane.java:260)
	at org.phoenicis.javafx.views.mainwindow.ui.MainWindowView.setCenter(MainWindowView.java:99)
	at org.phoenicis.javafx.views.mainwindow.ui.MainWindowView.showWait(MainWindowView.java:122)
	at org.phoenicis.javafx.controller.engines.EnginesController.populateView(EnginesController.java:136)
	at org.phoenicis.javafx.controller.engines.EnginesController.forceViewUpdate(EnginesController.java:206)
	at org.phoenicis.javafx.controller.engines.EnginesController.lambda$null$10(EnginesController.java:103)
	at org.phoenicis.engines.EnginesManager.lambda$getEngine$0(EnginesManager.java:71)
	at org.phoenicis.scripts.nashorn.NashornInteractiveSession.eval(NashornInteractiveSession.java:34)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$null$1(BackgroundScriptInterpreter.java:43)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
