### ISSUE TITLE
Cannot install a verb

### ISSUE THREAD

**Issue by qparis** [PhoenicisOrg/phoenicis#1598]
### Expected behavior
* Installation of the verb msls31 in the container

### Actual behavior
* An error is thrown: "Verb is not defined"

```
javax.script.ScriptException: ReferenceError: "Verb" is not defined in <eval> at line number 1
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:454)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.evalAndReturn(NashornEngine.java:59)
	at org.phoenicis.scripts.nashorn.NashornInteractiveSession.eval(NashornInteractiveSession.java:34)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$null$1(BackgroundScriptInterpreter.java:43)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: <eval>:1 ReferenceError: "Verb" is not defined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1441)
	at jdk.nashorn.internal.scripts.Script$193$\^eval\_.:program(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	... 10 more
```

<img width="472" alt="capture d ecran 2018-12-18 a 21 09 27" src="https://user-images.githubusercontent.com/373645/50180193-45136a00-0309-11e9-8f2c-7fd614d1574d.png">

### Steps to reproduce
* Open Phoenicis )
* Container -> Notepad++ > Verbs > msls31

### System information
* software version: commit b2cf1bb984a1d6bdfe220b43a5cd455dd44900fe (upstream/master)
* used operating system: macOS 
* used Java version: 8

**Comment by plata** [comment]
I cannot reproduce this. Are you sure your scripts are up to date?

**Comment by qparis** [comment]
Seems to work now. I assume you were probably right
