### ISSUE TITLE
Extractor is not able to extract .EXE

### ISSUE THREAD

**Issue by qparis** [PhoenicisOrg/phoenicis#1600]
### Expected behavior
- .EXE are extracted 

### Actual behavior
- .EXE are not extracted 

### Steps to reproduce
- Download https://web.archive.org/web/20130218065827if_/http://download.microsoft.com/download/winntwks40/paint/1/nt4/en-us/paintnt.exe 
- Extract with Extractor
- Exception is thrown 

### System information
N/A

**Comment by madoar** [comment]
Can you please post the thrown exception?

**Comment by plata** [comment]
Why do we have to extract it? Shouldn't it be an installer?

**Comment by qparis** [comment]
In many case, a .exe file is just a self-extracting .zip file. In these case, we prefer to extract it as it was a zip file. It is quicker, cleaner, and more user friendly (silent interface). Especially when the bundled unarchiver is not compatible with wine. 

Regarding the stacktrace: 

`[ERROR] org.phoenicis.javafx.views.common.ErrorMessage (l.76) - org.phoenicis.tools.archive.ArchiveException: Unable to extract the file
	at org.phoenicis.tools.archive.Zip.uncompress(Zip.java:98)
	at org.phoenicis.tools.archive.Zip.uncompressZipFile(Zip.java:46)
	at org.phoenicis.tools.archive.Extractor.uncompress(Extractor.java:65)
	at org.phoenicis.tools.archive.Extractor.uncompress(Extractor.java:45)
	at jdk.nashorn.internal.scripts.Script$Recompilation$241$3137$\^eval\_.extract-1([utils, functions, filesystem, extract]:140)
	at jdk.nashorn.internal.scripts.Script$Recompilation$200$715$\^eval\_.go([engines, wine, quick_script, zip_script]:60)
	at jdk.nashorn.internal.scripts.Script$Recompilation$189$215$\^eval\_.run(<eval>:9)
	at org.phoenicis.scripts.Installer$$NashornJavaAdapter.run(Unknown Source)
	at jdk.nashorn.internal.scripts.Script$164$\^eval\_.:program(<eval>:25)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.zip.ZipException: Unexpected record signature: 0X1F55A4D
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextZipEntry(ZipArchiveInputStream.java:260)
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextEntry(ZipArchiveInputStream.java:408)
	at org.phoenicis.tools.archive.Zip.uncompress(Zip.java:68)
	... 22 more`

**Comment by plata** [comment]
Is cabextract able to do this? I think we have an issue anyways to use a Java solution to extract archives.

**Comment by qparis** [comment]
Cabextract can extract cab compressed files. Some .exe will contain a zip archives, other will contain a .cab archive, so basically we are stuck.

Maybe you are right and we should use unzip / tar. However, the good thing with java is that we have a progressbar which is a really cool enhancement from POLv4
