### ISSUE TITLE
Release Alpha 2

### ISSUE THREAD

**Issue by qparis** [PhoenicisOrg/phoenicis#1683]

**Comment by qparis** [comment]
@plata Did you do the cherry-pick? I see Setup wizard: add a browser step (#1681) in the logs

**Comment by plata** [comment]
Yep. Only the pr you closed and the one in scripts is missing.

**Comment by qparis** [comment]
The PR won't be necessary, the two got mixed up

**Comment by plata** [comment]
Ok...

**Comment by qparis** [comment]
My bad sorry

**Comment by qparis** [comment]
The javafx.web package is missing in the release script (not related to GoG.com, it makes any webview crash). 
Do you want to cherry-pick the merge request or shall I add it manually for this time?

**Comment by plata** [comment]
Can you build the flatpak as well (description in the release docs)? And please upload the flatpak zip when release is finished.

**Comment by madoar** [comment]
The `deb` is working as intended.

**Comment by plata** [comment]
So the "unknown" is also fixed now?

**Comment by madoar** [comment]
No, the unknown is still there:
![grafik](https://user-images.githubusercontent.com/18488086/50565022-d384e400-0d2a-11e9-9eae-b48dd459591c.png)

**Comment by qparis** [comment]
> Can you build the flatpak as well (description in the release docs)? And please upload the flatpak zip when release is finished.

I'm on it

check that Notepad is listed with composed miniature (half Notepad++, half default)

What does that mean?

**Comment by plata** [comment]
The miniature should have on one side the Notepad++ logo and on the other side a different one.

**Comment by qparis** [comment]
It does not apparently:
Some other tests that are failing: 
* click “reset” (settings -> user interface) does not work 
* Confirmation popup randomly makes Phoenicis crash on macOS (I have already seen this before)

**Comment by plata** [comment]
Did you restart Phoenicis after "reset"? In any case, this is not really critical. About the macOS, no idea. I would say something to check for the next release.

**Comment by plata** [comment]
Branches should be ready now.

**Comment by qparis** [comment]
Concerning flatpak, I get 
linux.json --force-clean
Downloading sources
Initializing build dir
Committing stage init to cache
Starting build of org.phoenicis.playonlinux
========================================================================
Building module setup-compat-i386 in /home/playonlinux/phoenicis/phoenicis-dist/src/flatpak/.flatpak-builder/build/setup-compat-i386-1
========================================================================
Error: module setup-compat-i386: Invalid buildsystem: "simple"

**Comment by qparis** [comment]
The package do not support SSL requests (at least on macOS)

```
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:128)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:279)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2768)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2680)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1843)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
	at org.phoenicis.tools.http.Downloader.saveConnectionToStream(Downloader.java:214)
	... 23 more
```

**Comment by plata** [comment]
Which flatpak-builder version?

**Comment by qparis** [comment]
Flatpak 0.8.9

**Comment by plata** [comment]
Get a newer one: https://flatpak.org/setup/ E.g. for Ubuntu there's a PPA.

**Comment by qparis** [comment]
I'm on Debian...

**Comment by plata** [comment]
I don't know about Debian. But must be possible to use a newer version somehow...

**Comment by plata** [comment]
Did you check backports?

**Comment by qparis** [comment]
Yes. I will terminate tomorrow, tonight, nobody will be connected with the new year. 

One last thing, can someone test:

`new Downloader().url("https://cdn-hw.gog.com").get()`

with the package? It gives me a SSL handshake error and I think it could have other side effect

**Comment by plata** [comment]
I cannot check .deb so I guess @madoar will have to test.

**Comment by qparis** [comment]
The .tar.gz is also fine

**Comment by plata** [comment]
I can reproduce the issue.

**Comment by plata** [comment]
I assume that it cannot find the cacerts but this doesn't work somehow:
```
"-BjvmProperties=javax.net.ssl.trustStore=$PHOENICIS_TARGET/lib/security/cacerts"
```

**Comment by qparis** [comment]
It does because some https adresse are working:

new Downloader().url("https://www.playonlinux.com").get()

**Comment by plata** [comment]
Then I'm out of ideas.

**Comment by qparis** [comment]
I found were the problem was. It is just a module to add in the packaging file. I'll add it tomorrow, create a MR, recreate the debs and write the news at the same time.

**Comment by plata** [comment]
Ok. Currently I cannot even open the URL in a browser. Gives me 404.

**Comment by qparis** [comment]
So we are done for this ticket. Except that I don't know what to do once flatpak is built

**Comment by plata** [comment]
@qparis if you upload the flatpak zip, we can close this.

**Comment by qparis** [comment]
Done
