### ISSUE TITLE
Wine download failure 

### ISSUE THREAD

**Issue by Zemogiter** [PhoenicisOrg/phoenicis#1742]
### Expected behavior
Wine is downloaded during script execution
### Actual behavior
I get this error, tried with `Space Engineers` script using wine 4.0-rc4 and rc5, then 7-zip and got the same result.
```
javax.script.ScriptException: TypeError: Can not invoke method [jdk.dynalink.beans.OverloadedDynamicMethod
 String org.phoenicis.tools.http.Downloader.get(String,Consumer)
 String org.phoenicis.tools.http.Downloader.get(URL,Consumer)
 void org.phoenicis.tools.http.Downloader.get(String,String,Consumer)
 void org.phoenicis.tools.http.Downloader.get(URL,File,Consumer)
] with the passed arguments; they do not match any of its method signatures. in [utils, functions, net, download] at line number 124
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:477)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:461)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: [utils, functions, net, download]:124 TypeError: Can not invoke method [jdk.dynalink.beans.OverloadedDynamicMethod
 String org.phoenicis.tools.http.Downloader.get(String,Consumer)
 String org.phoenicis.tools.http.Downloader.get(URL,Consumer)
 void org.phoenicis.tools.http.Downloader.get(String,String,Consumer)
 void org.phoenicis.tools.http.Downloader.get(URL,File,Consumer)
] with the passed arguments; they do not match any of its method signatures.
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.linker.NashornBottomLinker.linkBean(NashornBottomLinker.java:120)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.linker.NashornBottomLinker.getGuardedInvocation(NashornBottomLinker.java:78)
	at jdk.dynalink/jdk.dynalink.linker.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:109)
	at jdk.dynalink/jdk.dynalink.LinkerServicesImpl.lambda$getGuardedInvocation$0(LinkerServicesImpl.java:137)
	at jdk.dynalink/jdk.dynalink.LinkerServicesImpl.getWithLookupInternal(LinkerServicesImpl.java:168)
	at jdk.dynalink/jdk.dynalink.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:135)
	at jdk.dynalink/jdk.dynalink.DynamicLinker.relink(DynamicLinker.java:242)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$223$2701$\^eval\_$cu1$restOf.get([utils, functions, net, download]:124)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$209$5556$\^eval\_$cu1$restOf.go([engines, wine, quick_script, steam_script]:109)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$184$400$\^eval\_.run(<eval>:13)
	at jdk.nashorn.javaadapters.org_phoenicis_scripts_Installer.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$183$\^eval\_$cu1$restOf.:program(<eval>:47)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:655)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:456)
	... 10 more
```
### Steps to reproduce
Run any script.
### System information
* software version (git revision) of phoenicis and scripts repositories
POL5 git revision af04922a4d717bca567b627aa95ae7972643dbb7:unknown and script repo 1a21498311caa2e44a1bf0121ad2e5f932e86734
* used operating system
Ubuntu 19.04 x64
* used Java version
```
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Ubuntu-3ubuntu1, mixed mode, sharing)
```

**Comment by plata** [comment]
@qparis your changes?

**Comment by Zemogiter** [comment]
@qparis It does match.

**Comment by Kreyren** [comment]
@Zemogiter Afaik there is none script for space enginners in phoenicis repo, willing to make one assuming feedback from you.

**Comment by Zemogiter** [comment]
@Kreyren I was talking about my script https://github.com/PhoenicisOrg/scripts/pull/725
But the same happens with other scripts (even if coresponding wine version is already downloaded).

**Comment by Kreyren** [comment]
@Zemogiter Noted

**Comment by qparis** [comment]
javax.script.ScriptException: TypeError: Can not invoke method [jdk.dynalink.beans.OverloadedDynamicMethod
 String org.phoenicis.tools.http.Downloader.get(String,Consumer)
 String org.phoenicis.tools.http.Downloader.get(URL,Consumer)
 void org.phoenicis.tools.http.Downloader.get(String,String,Consumer)
 void org.phoenicis.tools.http.Downloader.get(URL,File,Consumer)
]

Really teems to be a version mismatch. Can you show us your script repository configuration? What is your POL version?

**Comment by Zemogiter** [comment]
5.0-SNAPSHOT:unknown
Like I said before I've removed my local repo from settings in case it was causing the problem. There is just one entry:
git+https://github.com/PhoenicisOrg/scripts:master

**Comment by qparis** [comment]
Is your snapshot sync with the master?

**Comment by Zemogiter** [comment]
It appears this commit (https://github.com/PhoenicisOrg/phoenicis/commit/656602fc600a52717bd69f71ce4bfa586e84fed3) fixed the issue because the script installation now goes without issues. Also the POL version is now just 5.0-SNAPSHOT (without the unknown). Same for the git revision.
