### ISSUE TITLE
Flatpak version of your application : unable to install apps ...

### ISSUE THREAD

**Issue by aiamuzz** [PhoenicisOrg/phoenicis#1796]
Hi,

facing the following error when i tried installing apps on your newly created flatpak version of your app 

```
java.lang.RuntimeException: java.io.IOException: Cannot run program "/home/muz/.Phoenicis/engines//wine/upstream-linux-x86/3.0.4/bin/wine" (in directory "/home/muz/.Phoenicis/containers/wineprefix/Notepad"): error=2, No such file or directory
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.linker.JavaAdapterServices.wrapThrowable(JavaAdapterServices.java:285)
	at jdk.nashorn.javaadapters.org_phoenicis_engines_Engine.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$363$5021AAAZZA$\^eval\_.run([engines, wine, engine, object]:178)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$362$235A$\^eval\_$cu1$restOf.regedit#open([engines, wine, plugins, regedit]:12)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$349$336$\^eval\_$cu1$restOf.luna([engines, wine, verbs, luna]:29)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$318$553$\^eval\_$cu1$restOf.go([engines, wine, quick_script, installer_script]:72)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$259$223$\^eval\_.run(<eval>:9)
	at jdk.nashorn.javaadapters.org_phoenicis_scripts_Installer.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$258$\^eval\_$cu1$restOf.:program(<eval>:25)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:655)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:456)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at phoenicis.scripts@5.0-alpha-2/org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at phoenicis.scripts@5.0-alpha-2/org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at phoenicis.scripts@5.0-alpha-2/org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Cannot run program "/home/muz/.Phoenicis/engines//wine/upstream-linux-x86/3.0.4/bin/wine" (in directory "/home/muz/.Phoenicis/containers/wineprefix/Notepad"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$385$7115AAAZZA$\^eval\_$cu1$restOf.run([engines, wine, engine, implementation]:267)
	... 22 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 24 more

```

**Comment by plata** [comment]
This sounds like you're missing the compat extension. Please install `org.freedesktop.Platform.Compat.i386`.

**Comment by plata** [comment]
In my opinion yes. However that's a flatpak thing. See also https://github.com/flatpak/flatpak-builder/issues/223
Feel free to ask the flatpak devs again.

**Comment by aiamuzz** [comment]
> In my opinion yes. However that's a flatpak thing. See also [flatpak/flatpak-builder#223](https://github.com/flatpak/flatpak-builder/issues/223)
> Feel free to ask the flatpak devs again.

thanks @plata ... i guess then this is design decision on the part of the flatpak team ... 

until then could you please update your apps flathub with 'readme' info that this extension needs to be installed separately ?

Also you may want an additional command to show on your application flathub page along with the install command ... with a note saying this is a necessary extension ?

**Comment by plata** [comment]
Can you provide a pull request with a README how you would expect it?

**Comment by aiamuzz** [comment]
> Can you provide a pull request with a README how you would expect it?

done

**Comment by plata** [comment]
Thanks, I will have a look. Can we close this issue then?
