### ISSUE TITLE
Error when exiting Phoenicis 

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis#1817]
When I exit Phoenicis via a click on the `Close` button I get the following exception:

```
[INFO ] org.springframework.beans.factory.support.DisposableBeanAdapter (l.351) - Failed to invoke destroy method 'shutdown' on bean with name 'debugExecutorService'
java.lang.reflect.InaccessibleObjectException: Unable to make public void java.util.concurrent.Executors$DelegatedExecutorService.shutdown() accessible: module java.base does not "opens java.util.concurrent" to module spring.core
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
	at spring.core@5.1.4.RELEASE/org.springframework.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:499)
	at spring.beans@5.1.4.RELEASE/org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:336)
	at spring.beans@5.1.4.RELEASE/org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:271)
	at spring.beans@5.1.4.RELEASE/org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571)
	at spring.beans@5.1.4.RELEASE/org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543)
	at spring.beans@5.1.4.RELEASE/org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1052)
	at spring.beans@5.1.4.RELEASE/org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504)
	at spring.beans@5.1.4.RELEASE/org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1059)
	at spring.context@5.1.4.RELEASE/org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1035)
	at spring.context@5.1.4.RELEASE/org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1011)
	at spring.context@5.1.4.RELEASE/org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:961)
	at phoenicis.javafx@5.0-SNAPSHOT/org.phoenicis.javafx.JavaFXApplication.lambda$start$0(JavaFXApplication.java:52)
	at phoenicis.javafx@5.0-SNAPSHOT/org.phoenicis.javafx.controller.MainController.lambda$setOnClose$1(MainController.java:109)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at phoenicis.javafx@5.0-SNAPSHOT/org.phoenicis.javafx.dialogs.ConfirmDialog.showAndCallback(ConfirmDialog.java:53)
	at phoenicis.javafx@5.0-SNAPSHOT/org.phoenicis.javafx.controller.MainController.lambda$setOnClose$2(MainController.java:114)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/com.sun.javafx.stage.WindowPeerListener.closing(WindowPeerListener.java:93)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:147)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$4(GlassWindowEventHandler.java:176)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:174)
	at javafx.graphics/com.sun.glass.ui.Window.handleWindowEvent(Window.java:1346)
	at javafx.graphics/com.sun.glass.ui.Window.notifyClose(Window.java:1246)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by plata** [comment]
Assigned to @qparis because he implemented the `debugExecutorService`.

**Comment by qparis** [comment]
Hum, it seems that newSingleThreadPoolExecutor() does not properly exposes shutdown() method

**Comment by plata** [comment]
Do you still have this?

**Comment by madoar** [comment]
I don't occur this error anymore. I think I saw a commit of @qparis sometime ago that fixed this

**Comment by plata** [comment]
Just started with `mvn:exec` and closed again. Gave me:
```
[WARNING] thread Thread[ForkJoinPool.commonPool-worker-3,5,org.phoenicis.javafx.JavaFXApplication] was interrupted but is still alive after waiting at least 15000msecs
[WARNING] thread Thread[ForkJoinPool.commonPool-worker-3,5,org.phoenicis.javafx.JavaFXApplication] will linger despite being asked to die via interruption
[WARNING] NOTE: 1 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=org.phoenicis.javafx.JavaFXApplication,maxpri=10]
java.lang.IllegalThreadStateException
    at java.lang.ThreadGroup.destroy (ThreadGroup.java:776)
    at org.codehaus.mojo.exec.ExecJavaMojo.execute (ExecJavaMojo.java:321)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

**Comment by madoar** [comment]
This seems to be a new and unrelated error right?

**Comment by plata** [comment]
Could be. Do you get the same?

**Comment by madoar** [comment]
It doesn't work for me, but I think I got the command wrong.

When I run `mvn exec:java` in the parent repository I get:

```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project phoenicis: The parameters 'mainClass' for goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java are missing or invalid -> [Help 1]
```

When I run the command in `phoenicis-javafx` I get:

```
[ERROR] Failed to execute goal on project phoenicis-javafx: Could not resolve dependencies for project org.phoenicis:phoenicis-javafx:jar:5.0-SNAPSHOT: The following artifacts could not be resolved: org.phoenicis:phoenicis-configuration:jar:5.0-SNAPSHOT, org.phoenicis:phoenicis-repository:jar:5.0-SNAPSHOT, org.phoenicis:phoenicis-scripts:jar:5.0-SNAPSHOT, org.phoenicis:phoenicis-library:jar:5.0-SNAPSHOT, org.phoenicis:phoenicis-engines:jar:5.0-SNAPSHOT, org.phoenicis:phoenicis-containers:jar:5.0-SNAPSHOT, org.phoenicis:phoenicis-settings:jar:5.0-SNAPSHOT: Failure to find org.phoenicis:phoenicis-configuration:jar:5.0-SNAPSHOT in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced -> [Help 1]
```

I called `mvn clean package` before

**Comment by plata** [comment]
You need `mvn install`.

**Comment by madoar** [comment]
Using:

```bash
mvn clean
mvn clean package
mvn install
cd phoenicis-javafx
mvn exec:java
```

starts Phoenicis without any errors

**Comment by plata** [comment]
Does it also close without errors?

**Comment by madoar** [comment]
The window closes without errors but it doesn't seem to terminate the application

**Comment by plata** [comment]
Mh.
