### ISSUE TITLE
Scripts repo does not properly sync when installed from flathub

### ISSUE THREAD

**Issue by seijikun** [PhoenicisOrg/phoenicis#1835]
### Expected behavior
When first starting Phoenicis, the scripts repo should properly sync, so that Phoenicis can provide a list of supported applications.

### Actual behavior
When phoenicis is installed from flathub:
```
org.freedesktop.Platform/x86_64/18.08              flathub 30d1e0e6f128
org.freedesktop.Platform.Locale/x86_64/18.08       flathub 3756db4fedc7
org.gtk.Gtk3theme.Breeze-Dark/x86_64/3.22          flathub 7829afc2ec4d
org.freedesktop.Platform.html5-codecs/x86_64/18.08 flathub 337041240b18
org.phoenicis.playonlinux/x86_64/stable            flathub 95e86572d1f4
  permissions: ipc, network, x11, dri, multiarch
  file access: xdg-documents, xdg-download
org.freedesktop.Platform.Compat.i386/x86_64/18.08  flathub 1b146d994719
```
Phoenicis instantly shows the following error message:
```
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/seiji/.Phoenicis/cache/git-298283780/Applications/Games/Batman™: Arkham Origins/Steam/._script.js2250126233507824069.tmp
	at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:145)
	at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:280)
	at java.base/java.io.File.toPath(File.java:2290)
	at org.eclipse.jgit@5.2.0.201812061821-r/org.eclipse.jgit.util.FileUtils.isFile(FileUtils.java:736)
	at org.eclipse.jgit@5.2.0.201812061821-r/org.eclipse.jgit.util.FileUtils.canExecute(FileUtils.java:748)
	at org.eclipse.jgit@5.2.0.201812061821-r/org.eclipse.jgit.util.FS_POSIX.canExecute(FS_POSIX.java:238)
	at org.eclipse.jgit@5.2.0.201812061821-r/org.eclipse.jgit.dircache.DirCacheCheckout.checkoutEntry(DirCacheCheckout.java:1513)
	at org.eclipse.jgit@5.2.0.201812061821-r/org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:577)
	at org.eclipse.jgit@5.2.0.201812061821-r/org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:484)
	at org.eclipse.jgit@5.2.0.201812061821-r/org.eclipse.jgit.api.CloneCommand.checkout(CloneCommand.java:362)
	at org.eclipse.jgit@5.2.0.201812061821-r/org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:225)
	at phoenicis.repository@5.0-alpha-2/org.phoenicis.repository.types.GitRepository.cloneOrUpdate(GitRepository.java:125)
	at phoenicis.repository@5.0-alpha-2/org.phoenicis.repository.types.GitRepository.cloneOrUpdateWithLock(GitRepository.java:93)
	at phoenicis.repository@5.0-alpha-2/org.phoenicis.repository.types.GitRepository.fetchInstallableApplications(GitRepository.java:162)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:178)
	at java.base/java.util.stream.ReferencePipeline.lambda$collect$1(ReferencePipeline.java:575)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

```

### Steps to reproduce
Install Phoenicis from flathub:
```
flatpak install flathub org.phoenicis.playonlinux
```
Start phoenicis:
```
flatpak run org.phoenicis.playonlinux
```

### System information
* used operating system
> openSUSE Tumbleweed
* used Java version
> openSUSE does not provide JavaFX, so I guess it's the bundled one from the flathub packet?

**Comment by plata** [comment]
Can you test with a local scripts checkout and delete the batman games? I could imagine that it is caused by "™". Strange why others don't see this problem though.

**Comment by madoar** [comment]
This seems to be temporary file created by `jgit` during the clone

**Comment by seijikun** [comment]
Sure! I went to
```
~/.var/app/org.phoenicis.playonlinux/.Phoenicis/cache/git-...
```
and noticed, that everything seems to have been correctly cloned (`git pull` did nothing) the Batman folder indeed does not show the `™` sign. It instead shows a `?`.

I deleted all files / folders except the `.git` folder, and ran:
```
git checkout master
```
Now the Batman-Folder seems to be encoded properly (it is showing the `™` now)

**Comment by madoar** [comment]
Does the error occur again if you delete the whole `git-298283780` folder and let Phoenicis perform the clone?

**Comment by seijikun** [comment]
Yes, and the encoding is destroyed again.

**Comment by seijikun** [comment]
I just found something interesting:
I have
```
LANG=de_DE.UTF-8
```
But when I run phoenicis like follows (cache folder deleted again):
```
LANG=en_US.UTF-8 flatpak run org.phoenicis.playonlinux
```
checkout succeeds and everything works.

**Comment by plata** [comment]
I think we should simply remove the "tm" from the directory name.

**Comment by rodneyrod** [comment]
Having a similar issue in flatpak on Arch

**Comment by plata** [comment]
@rodneyrod also with the encoding?

**Comment by rodneyrod** [comment]
Well, it doesn't automatically download applications or games, and when I try and do a manual refresh of the repos, the program hangs and crashes

**Comment by i-need-to-tell-you-something** [comment]
Flatpak is broken for me on Kubuntu 18.04 as well with the Batman (tm) error. `LANG=en_US.UTF-8 flatpak run org.phoenicis.playonlinux` didn't help.
<details>
<summary markdown="span">My locale:</summary>

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_DK.UTF-8
LC_COLLATE=en_US.UTF-8
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=et_EE.UTF-8
LC_NAME=et_EE.UTF-8
LC_ADDRESS=et_EE.UTF-8
LC_TELEPHONE=et_EE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=et_EE.UTF-8
LC_ALL=
```

</details>

**Comment by plata** [comment]
Maybe we should just remove UTF-8 stuff from the directory names. Could you check if that solves the issues for you? Or do you still get UTF-8 problems in other places?
