### ISSUE TITLE
Phoenicis freezes during Wine (x86) install

### ISSUE THREAD

**Issue by jebeld17** [PhoenicisOrg/phoenicis#1913]
### Expected behavior
Phoenicis should download and install the latest variant of Wine (x86) during a Custom Wine 32-Bit (x86) install.

### Actual behavior
Phoenicis freezes at the "please wait while wine?os=linux is downloaded..." step with no estimated time of completion. 

`javax.script.ScriptException: SyntaxError: Invalid JSON: <json>:1:0 Expected json literal but found 
gz",
^ in [engines, wine, engine, object] at line number 273
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:477)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:461)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at phoenicis.scripts@5.0-alpha-2/org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at phoenicis.scripts@5.0-alpha-2/org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at phoenicis.scripts@5.0-alpha-2/org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: [engines, wine, engine, object]:273 SyntaxError: Invalid JSON: <json>:1:0 Expected json literal but found 
gz",
^
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.syntaxError(ECMAErrors.java:160)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.syntaxError(ECMAErrors.java:145)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.JSONFunctions.parse(JSONFunctions.java:81)
	at jdk.scripting.nashorn/jdk.nashorn.internal.objects.NativeJSON.parse(NativeJSON.java:118)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$864$8931A$\^eval\_$cu1$restOf.availableDistributions([engines, wine, engine, object]:273)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$685$553$\^eval\_$cu1$restOf.go([engines, wine, quick_script, installer_script]:42)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$627$273$\^eval\_.run(<eval>:10)
	at jdk.nashorn.javaadapters.org_phoenicis_scripts_Installer.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$621$\^eval\_$cu1$restOf.:program(<eval>:29)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:655)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:456)
	... 10 more
Caused by: jdk.nashorn.internal.runtime.ParserException: <json>:1:0 Expected json literal but found 
gz",
^
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.JSONParser.error(JSONParser.java:529)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.JSONParser.error(JSONParser.java:533)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.JSONParser.expectedError(JSONParser.java:541)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.JSONParser.parseLiteral(JSONParser.java:182)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.JSONParser.parse(JSONParser.java:148)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.JSONFunctions.parse(JSONFunctions.java:79)
	... 20 more
`

**Comment by jebeld17** [comment]
[hardinfo_report.zip](https://github.com/PhoenicisOrg/phoenicis/files/3027307/hardinfo_report.zip)

**Comment by plata** [comment]
This seems to happen when the Wine versions json is read:
https://github.com/PhoenicisOrg/scripts/blob/5807762485e61706cbbc265f9c80a146e5fa509b/Engines/Wine/Engine/Object/script.js#L274
Therefore, I assume that it's an error in the json really and I will move this issue to the winebuild repo.
