### ISSUE TITLE
Cannot build phoenicis on ubuntu 19.04

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/phoenicis#1956]
### Expected behavior
Build phoenicis
### Actual behavior
Fails with (test):
```
[INFO] Running org.phoenicis.javafx.AppConfigurationInitialisationTest
java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
        at org.testfx.util.WaitForAsyncUtils$ASyncFXCallable.get(WaitForAsyncUtils.java:715)
        at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:298)
        at org.testfx.api.FxToolkit.waitForSetup(FxToolkit.java:245)
        at org.testfx.api.FxToolkit.setupFixture(FxToolkit.java:202)
        at org.phoenicis.javafx.AppConfigurationInitialisationTest.testAppConfigurationInitialisation(AppConfigurationInitialisationTest.java:49)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 32.803 s <<< FAILURE! - in org.phoenicis.javafx.AppConfigurationInitialisationTest
[ERROR] testAppConfigurationInitialisation(org.phoenicis.javafx.AppConfigurationInitialisationTest)  Time elapsed: 32.309 s  <<< FAILURE!
java.lang.AssertionError
        at org.phoenicis.javafx.AppConfigurationInitialisationTest.testAppConfigurationInitialisation(AppConfigurationInitialisationTest.java:52)
```
### System information
* software version (git revision) of phoenicis and scripts repositories https://github.com/PhoenicisOrg/phoenicis/commit/ac0e31986e720db96642c56fdbdf453bf5c78822
* used operating system ubuntu 19.04
* used Java version https://download.java.net/openjdk/jdk11/ri/openjdk-11+28_linux-x64_bin.tar.gz

**Comment by qparis** [comment]
Same problem on macOS

**Comment by plata** [comment]
Does it help if you increase the timeout?
- https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#forkedProcessTimeoutInSeconds
- or: @Test(timeout=2000000) in https://github.com/PhoenicisOrg/phoenicis/blob/ac0e31986e720db96642c56fdbdf453bf5c78822/phoenicis-javafx/src/test/java/org/phoenicis/javafx/AppConfigurationInitialisationTest.java#L46

**Comment by ImperatorS79** [comment]
I used 200000000 and it still fails.

**Comment by plata** [comment]
Did you also try the maven setting?

**Comment by ImperatorS79** [comment]
How do I do that ?

**Comment by plata** [comment]
In https://github.com/PhoenicisOrg/phoenicis/blob/bd9af0cd71e4f7a2a111684603e51cd9ee8abe20/pom.xml#L230
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>${surefire.version}</version>
    <configuration>
        <argLine>--add-exports javafx.graphics/com.sun.javafx.application=org.testfx</argLine>
        <forkedProcessTimeoutInSeconds>2000</forkedProcessTimeoutInSeconds>
    </configuration>
</plugin>
```

**Comment by ImperatorS79** [comment]
Still fails with 2000. With 20000000 I have:
Results in build failure in phoenicis-configuration:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project phoenicis-configuration: There was a timeout or other error in the fork -> [Help 1]
```

**Comment by plata** [comment]
Does it also take longer before this error appears? The timeout should be in seconds.

**Comment by ImperatorS79** [comment]
It did not take 2000 seconds I think ^^.

**Comment by plata** [comment]
Mh. Does this help: https://howtodoinjava.com/junit/how-to-force-timeout-in-jnuit-testcase-execution/ ?

I do not have this issue on Manjaro...

**Comment by Zemogiter** [comment]
In my case writing `@Test(timeout=2000000)` above the ` public void testAppConfigurationInitialisation() { ` in https://github.com/PhoenicisOrg/phoenicis/blob/ac0e31986e720db96642c56fdbdf453bf5c78822/phoenicis-javafx/src/test/java/org/phoenicis/javafx/AppConfigurationInitialisationTest.java#L46 fixed the issue. Fresh ubuntu 19.04 installation on a laptop.

**Comment by qparis** [comment]
@plata maybe we should disable this test for now?

**Comment by plata** [comment]
I don't know. It is really the only test checking that Phoenicis is not completely broken.

**Comment by madoar** [comment]
I think the test is too broad (it should not test the complete startup). I think that we should replace it with multiple tests checking that certain parts of the startup are not broken:

- fetching repositories (requires mocking)
- loading (and potentially updating) the different feature panels (library, apps, ...)

Until we provide dedicated tests for these areas we shouldn't remove the old one I believe.

**Comment by qparis** [comment]
This should be pretty straightforward to do, considering that we have all the required interface to mock setupwizard

**Comment by vaidis** [comment]
same problem on linux mint 19 (x64)

**Comment by plata** [comment]
@vaidis does this help in your case: https://github.com/PhoenicisOrg/phoenicis/issues/1956#issuecomment-500462764 ?

**Comment by Zemogiter** [comment]
@vaidis try compiling the source code with `mvn -DskipTests clean package`
