### ISSUE TITLE
Potential GraalVM issue

### ISSUE THREAD

**Issue by Zemogiter** [PhoenicisOrg/phoenicis#1988]
### Expected behavior
After runtime setup the installation file for the software should be executed
### Actual behavior
~~That step is skiped and we get the "file not found" error which in case of an online Starcraft 2 script looks like this:~~ Looks like this was fixed in the #1994 
```
Executable Battle.net.exe not found!
	at com.oracle.truffle.js.runtime.UserScriptException.create(UserScriptException.java:74)
	at com.oracle.truffle.js.nodes.control.ThrowNode.execute(ThrowNode.java:106)
	at com.oracle.truffle.js.nodes.JavaScriptNode.executeVoid(JavaScriptNode.java:212)
	at com.oracle.truffle.js.nodes.control.IfNode.executeVoid(IfNode.java:161)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:74)
	at com.oracle.truffle.js.nodes.control.BlockNode.execute(BlockNode.java:62)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:66)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
	at <js> :program(Unknown)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.executeVoid(Value.java:358)
	at org.phoenicis.scripts.Installer$$JSJavaAdapter.run(Unknown Source)
	at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:367)
	at org.phoenicis.scripts.engine.implementation.PolyglotScriptEngine.eval(PolyglotScriptEngine.java:63)
	at org.phoenicis.scripts.interpreter.PhoenicisScriptInterpreter.runScript(PhoenicisScriptInterpreter.java:36)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:37)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by host exception: com.oracle.truffle.js.runtime.UserScriptException: Executable Battle.net.exe not found!
```
In case of Steam version of Star Trek Online it looks slighty different:
```
/home/jonasz/.Phoenicis/containers/wineprefix/Star Trek Online/drive_c/Program Files/Steam/Steam.exe (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.phoenicis.tools.win32.ExeAnalyser.isArchitecture(ExeAnalyser.java:61)
	at org.phoenicis.tools.win32.ExeAnalyser.is64Bits(ExeAnalyser.java:46)
	at <js> run(engines.wine.engine.implementation:323:13179-13231)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.execute(Value.java:338)
	at org.phoenicis.engines.Engine$$JSJavaAdapter.run(Unknown Source)
	at <js> Wine.run(engines.wine.engine.object:178:5495-5585)
	at <js> Wine.runInsidePrefix(engines.wine.engine.object:146:4573-4674)
	at <js> SteamScript.go(engines.wine.quick_script.steam_script:137:7446-7537)
	at <js> run(Unnamed:9-16:282-544)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.executeVoid(Value.java:358)
	at org.phoenicis.scripts.Installer$$JSJavaAdapter.run(Unknown Source)
	at <js> :program(Unnamed:23:670-690)
	at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:367)
	at org.phoenicis.scripts.engine.implementation.PolyglotScriptEngine.eval(PolyglotScriptEngine.java:63)
	at org.phoenicis.scripts.interpreter.PhoenicisScriptInterpreter.runScript(PhoenicisScriptInterpreter.java:36)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:37)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by host exception: java.io.FileNotFoundException: /home/jonasz/.Phoenicis/containers/wineprefix/Star Trek Online/drive_c/Program Files/Steam/Steam.exe (No such file or directory)
```
This is the result of Civilization 5 installation, on the commit https://github.com/PhoenicisOrg/phoenicis/commit/3106ef2f78a7b39775a3e037ce6b5f9137350c2b
```
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - java.lang.InterruptedException
	at org.phoenicis.scripts.ui.Message.block(Message.java:35)
	at org.phoenicis.scripts.ui.UiMessageSender.runAndWait(UiMessageSender.java:33)
	at org.phoenicis.scripts.wizard.UiSetupWizardImplementation.menu(UiSetupWizardImplementation.java:261)
	at org.phoenicis.scripts.wizard.UiSetupWizardImplementation.menu(UiSetupWizardImplementation.java:246)
	at <js> changeVersion(engines.wine.engine.implementation:418:17354-17473)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.executeVoid(Value.java:360)
	at org.phoenicis.engines.Engine$$JSJavaAdapter.changeVersion(Unknown Source)
	at org.phoenicis.javafx.components.container.control.ContainersFeaturePanel.lambda$changeEngineVersion$9(ContainersFeaturePanel.java:169)
	at org.phoenicis.engines.EnginesManager.lambda$getEngine$0(EnginesManager.java:72)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by host exception: org.phoenicis.scripts.interpreter.ScriptException: java.lang.InterruptedException

Exception in thread "pool-3-thread-9" java.lang.InterruptedException
	at org.phoenicis.scripts.ui.Message.block(Message.java:35)
	at org.phoenicis.scripts.ui.UiMessageSender.runAndWait(UiMessageSender.java:33)
	at org.phoenicis.scripts.wizard.UiSetupWizardImplementation.menu(UiSetupWizardImplementation.java:261)
	at org.phoenicis.scripts.wizard.UiSetupWizardImplementation.menu(UiSetupWizardImplementation.java:246)
	at <js> changeVersion(engines.wine.engine.implementation:418:17354-17473)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.executeVoid(Value.java:360)
	at org.phoenicis.engines.Engine$$JSJavaAdapter.changeVersion(Unknown Source)
	at org.phoenicis.javafx.components.container.control.ContainersFeaturePanel.lambda$changeEngineVersion$9(ContainersFeaturePanel.java:169)
	at org.phoenicis.engines.EnginesManager.lambda$getEngine$0(EnginesManager.java:72)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by host exception: org.phoenicis.scripts.interpreter.ScriptException: java.lang.InterruptedException
```
### Steps to reproduce
Affects OriginScript (tested with SimCity), SteamScript (tested with Civ5), Uplay (Anno 2070) and OnlineInstallerScript(DC Universe Online). ~~Haven't checked local script yet.~~ Local script for Anno 2070 crashes with this error:
```
java.lang.IllegalAccessException: access to public member failed: sun.awt.SunToolkit.getScreenSize[Ljava.lang.Object;@4fb8911e/invokeVirtual, from public Lookup
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostMethodDesc$SingleMethod$MethodMHImpl.makeMethodHandle(HostMethodDesc.java:318)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostMethodDesc$SingleMethod$MHBase.invoke(HostMethodDesc.java:258)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostExecuteNode$1.executeImpl(HostExecuteNode.java:776)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.GuestToHostRootNode.execute(GuestToHostRootNode.java:87)
	at <js> :anonymous(Unnamed:25:951-1002)
	at <js> InstallerScript.go(engines.wine.quick_script.installer_script:75:3166-3200)
	at <js> run(Unnamed:15-40:534-1793)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.executeVoid(Value.java:358)
	at org.phoenicis.scripts.Installer$$JSJavaAdapter.run(Unknown Source)
	at <js> :program(Unnamed:47:1919-1939)
	at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:367)
	at org.phoenicis.scripts.engine.implementation.PolyglotScriptEngine.eval(PolyglotScriptEngine.java:63)
	at org.phoenicis.scripts.interpreter.PhoenicisScriptInterpreter.runScript(PhoenicisScriptInterpreter.java:36)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:37)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by host exception: java.lang.IllegalStateException: java.lang.IllegalAccessException: access to public member failed: sun.awt.SunToolkit.getScreenSize[Ljava.lang.Object;@4fb8911e/invokeVirtual, from public Lookup
```
### System information
* software version (git revision) of phoenicis and scripts repositories
https://github.com/PhoenicisOrg/phoenicis/commit/b246b865ce06d886a53bbd5a618274674c751fc2
script repo https://github.com/PhoenicisOrg/scripts/commit/53a6846f18c9841225d063a1a5d15c7aa94abbdd
* used operating system
Ubuntu 19.04 x64
* used Java version
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu219.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu219.04.1, mixed mode, sharing)

**Comment by Zemogiter** [comment]
I cannot reproduce this issue anymore. Closing for now.
