### ISSUE TITLE
Shortcuts and launch exe file button don't work

### ISSUE THREAD

**Issue by Zemogiter** [PhoenicisOrg/phoenicis#1997]
### Expected behavior
The Battle.net app shows up when clicking on play button
### Actual behavior
No game processes in system monitor and this in terminal output:
```
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - TypeError: Cannot read property 'progressBar' of null
	at com.oracle.truffle.js.runtime.JSException.create(JSException.java:100)
	at com.oracle.truffle.js.runtime.Errors.createTypeError(Errors.java:107)
	at com.oracle.truffle.js.runtime.Errors.createTypeErrorCannotGetProperty(Errors.java:409)
	at com.oracle.truffle.js.nodes.access.PropertyGetNode$TypeErrorPropertyGetNode.getValue(PropertyGetNode.java:768)
	at com.oracle.truffle.js.nodes.access.PropertyGetNode.getValue(PropertyGetNode.java:198)
	at com.oracle.truffle.js.nodes.access.PropertyNode.executeWithTarget(PropertyNode.java:136)
	at com.oracle.truffle.js.nodes.access.PropertyNode.executeWithTarget(PropertyNode.java:128)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.executeFunctionWithTarget(JSFunctionCallNode.java:719)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:706)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute_generic4(JSWriteCurrentFrameSlotNodeGen.java:177)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute(JSWriteCurrentFrameSlotNodeGen.java:93)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.executeVoid(JSWriteCurrentFrameSlotNodeGen.java:343)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:74)
	at com.oracle.truffle.js.nodes.control.BlockNode.execute(BlockNode.java:62)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:66)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
	at <js> Wine.run(Unknown)
	at <js> this.run(engines.wine.shortcuts.reader:31-33:1056-1222)
	at <js> ShortcutReader.run(engines.wine.shortcuts.reader:98:2952-2982)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.execute(Value.java:338)
	at org.phoenicis.engines.Engine$$JSJavaAdapter.run(Unknown Source)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:429)
	at org.phoenicis.library.ShortcutRunner.lambda$run$0(ShortcutRunner.java:50)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by host exception: com.oracle.truffle.js.runtime.JSException: TypeError: Cannot read property 'progressBar' of null

Exception in thread "pool-3-thread-5" TypeError: Cannot read property 'progressBar' of null
	at com.oracle.truffle.js.runtime.JSException.create(JSException.java:100)
	at com.oracle.truffle.js.runtime.Errors.createTypeError(Errors.java:107)
	at com.oracle.truffle.js.runtime.Errors.createTypeErrorCannotGetProperty(Errors.java:409)
	at com.oracle.truffle.js.nodes.access.PropertyGetNode$TypeErrorPropertyGetNode.getValue(PropertyGetNode.java:768)
	at com.oracle.truffle.js.nodes.access.PropertyGetNode.getValue(PropertyGetNode.java:198)
	at com.oracle.truffle.js.nodes.access.PropertyNode.executeWithTarget(PropertyNode.java:136)
	at com.oracle.truffle.js.nodes.access.PropertyNode.executeWithTarget(PropertyNode.java:128)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.executeFunctionWithTarget(JSFunctionCallNode.java:719)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:706)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute_generic4(JSWriteCurrentFrameSlotNodeGen.java:177)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute(JSWriteCurrentFrameSlotNodeGen.java:93)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.executeVoid(JSWriteCurrentFrameSlotNodeGen.java:343)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:74)
	at com.oracle.truffle.js.nodes.control.BlockNode.execute(BlockNode.java:62)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:66)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
	at <js> Wine.run(Unknown)
	at <js> this.run(engines.wine.shortcuts.reader:31-33:1056-1222)
	at <js> ShortcutReader.run(engines.wine.shortcuts.reader:98:2952-2982)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.execute(Value.java:338)
	at org.phoenicis.engines.Engine$$JSJavaAdapter.run(Unknown Source)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:429)
	at org.phoenicis.library.ShortcutRunner.lambda$run$0(ShortcutRunner.java:50)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by host exception: com.oracle.truffle.js.runtime.JSException: TypeError: Cannot read property 'progressBar' of null
```
### Steps to reproduce
Install Starcraft 2 online script and once it installs press play.
### System information
* software version (git revision) of phoenicis and scripts repositories
https://github.com/PhoenicisOrg/phoenicis/commit/3106ef2f78a7b39775a3e037ce6b5f9137350c2b
scripts repo https://github.com/PhoenicisOrg/scripts/commit/4ddf348d5aa8688b1bd30f8606442624d6b7a90b
* used operating system
Ubuntu 19.04 x64
* used Java version
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu219.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu219.04.1, mixed mode, sharing)
jonasz@

**Comment by plata** [comment]
Is this only affecting Starcraft 2 Online or also other apps?

Can anybody see where in the code there error is coming from? It says something about `Wine.run` but I do not see any `progressBar` there.

**Comment by ImperatorS79** [comment]
It seems to be the shortcut reader who fails somehow.

**Comment by plata** [comment]
Also there I cannot see a `progressBar`.

**Comment by Zemogiter** [comment]
Space Engineers, The Sims 3 and Anno 2070 are also affected. Safe to say that this issue affects every shortcut.

**Comment by ImperatorS79** [comment]
Extractor, Downloader and Checksum use progressBar.

**Comment by plata** [comment]
I cannot reproduce this anymore. When I tried for the first time, I also had this but not now. Not sure what I did though... Using current master for both the software and scripts.

**Comment by ImperatorS79** [comment]
Well, for me nothing happens and there is no error when I try to run a shortcut.

**Comment by Zemogiter** [comment]
Updated both scripts and the app to the latest commit still getting this error.

**Comment by plata** [comment]
@ImperatorS79 are you using Ubuntu as well (I'm on Manjaro)? Also: how to you start Phoenicis? I've been running from IntelliJ IDEA.

**Comment by ImperatorS79** [comment]
I am using ubuntu and I use the .deb.

**Comment by plata** [comment]
I just tried again with `mvn exec:java`. First try: error occurs. Click "Run" again: works. After that it works all the time.

**Comment by Zemogiter** [comment]
SimCity 2013 shortcut is working oddly enough. Same for The Sims 2, The Sims 3, Lego Rock Raiders, Anno 2070 and Space Engineers. RimWorld (error in the OP) and Starcraft 2 (no error and no process in system monitor)

**Comment by plata** [comment]
Ok... What's the difference?

**Comment by Zemogiter** [comment]
Now this error seems to affect ony RimWorld shortcut.
```
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - TypeError: invokeMember on JavaObject[org.phoenicis.engines.Engine$$JSJavaAdapter@4d1f01e (org.phoenicis.engines.Engine$$JSJavaAdapter)] failed due to: UnsupportedTypeException
	at <js> Wine.run(engines.wine.engine.object:178:5497-5587)
	at <js> run(engines.wine.shortcuts.reader:33-35:1003-1169)
	at <js> run(engines.wine.shortcuts.reader:106:2973-3002)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:429)
	at org.phoenicis.library.ShortcutRunner.lambda$run$0(ShortcutRunner.java:50)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Exception in thread "pool-3-thread-10" TypeError: invokeMember on JavaObject[org.phoenicis.engines.Engine$$JSJavaAdapter@4d1f01e (org.phoenicis.engines.Engine$$JSJavaAdapter)] failed due to: UnsupportedTypeException
	at <js> Wine.run(engines.wine.engine.object:178:5497-5587)
	at <js> run(engines.wine.shortcuts.reader:33-35:1003-1169)
	at <js> run(engines.wine.shortcuts.reader:106:2973-3002)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:429)
	at org.phoenicis.library.ShortcutRunner.lambda$run$0(ShortcutRunner.java:50)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by madoar** [comment]
Most likely one of the passed parameters to `this._implementation.run` inside `Wine` is of a type that the Java `Engine` interface does not accept. Can you try if https://github.com/PhoenicisOrg/scripts/pull/1018 and https://github.com/PhoenicisOrg/phoenicis/pull/2010 fixes the problem?

**Comment by Zemogiter** [comment]
Now I get different error:
```
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - TypeError: invokeMember on JavaObject[org.phoenicis.tools.files.FileUtilities@6bbcede9 (org.phoenicis.tools.files.FileUtilities)] failed due to: Unknown identifier: exists
	at <js> fileExists(utils.functions.filesystem.files:32:727-756)
	at <js> run(engines.wine.engine.implementation:310:11794-11830)
	at <js> Wine.run(engines.wine.engine.object:178:5501-5591)
	at <js> run(engines.wine.shortcuts.reader:34-36:889-1037)
	at <js> run(engines.wine.shortcuts.reader:103:2488-2517)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:429)
	at org.phoenicis.library.ShortcutRunner.lambda$run$0(ShortcutRunner.java:50)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Exception in thread "pool-3-thread-8" TypeError: invokeMember on JavaObject[org.phoenicis.tools.files.FileUtilities@6bbcede9 (org.phoenicis.tools.files.FileUtilities)] failed due to: Unknown identifier: exists
	at <js> fileExists(utils.functions.filesystem.files:32:727-756)
	at <js> run(engines.wine.engine.implementation:310:11794-11830)
	at <js> Wine.run(engines.wine.engine.object:178:5501-5591)
	at <js> run(engines.wine.shortcuts.reader:34-36:889-1037)
	at <js> run(engines.wine.shortcuts.reader:103:2488-2517)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:429)
	at org.phoenicis.library.ShortcutRunner.lambda$run$0(ShortcutRunner.java:50)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by plata** [comment]
It tries to call `exists` on `FileUtilities`? This should be a Java `File`...
https://github.com/PhoenicisOrg/scripts/blob/99abb1267b1978e0008c1b0177cdb0d2d92a4294/Utils/Functions/Filesystem/Files/script.js#L31

**Comment by madoar** [comment]
@plata this is not the case when he is using PhoenicisOrg/scripts#1018 (see https://github.com/PhoenicisOrg/phoenicis/issues/1997#issuecomment-505632881)

**Comment by Zemogiter** [comment]
Blocked untile #2010 and https://github.com/PhoenicisOrg/scripts/pull/1018 are merged.

**Comment by Zemogiter** [comment]
After updating POL to the latest commit I get a different error:
```
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - TypeError: com.oracle.truffle.api.interop.UnsupportedTypeException: Cannot convert '8930'(language: JavaScript, type: number) to Java type 'java.lang.String': Invalid or lossy primitive coercion.
	at <js> run(engines.wine.engine.implementation:398:15684-15732)
	at <js> Wine.run(engines.wine.engine.object:178:5501-5591)
	at <js> run(engines.wine.shortcuts.reader:38-40:1119-1283)
	at <js> run(engines.wine.shortcuts.reader:106:3053-3082)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:429)
	at org.phoenicis.library.ShortcutRunner.lambda$run$0(ShortcutRunner.java:50)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Exception in thread "pool-3-thread-5" TypeError: com.oracle.truffle.api.interop.UnsupportedTypeException: Cannot convert '8930'(language: JavaScript, type: number) to Java type 'java.lang.String': Invalid or lossy primitive coercion.
	at <js> run(engines.wine.engine.implementation:398:15684-15732)
	at <js> Wine.run(engines.wine.engine.object:178:5501-5591)
	at <js> run(engines.wine.shortcuts.reader:38-40:1119-1283)
	at <js> run(engines.wine.shortcuts.reader:106:3053-3082)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:429)
	at org.phoenicis.library.ShortcutRunner.lambda$run$0(ShortcutRunner.java:50)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by plata** [comment]
Can you add some print outs to find out which variable/line is the issue? Line 398 doesn't make any sense to me currently.
Relevant code is:
https://github.com/PhoenicisOrg/scripts/blob/e4583677b9c3dcb730da4f135451d21587fe2604/Engines/Wine/Engine/Implementation/script.js#L343

**Comment by Zemogiter** [comment]
But line 398 is just an empty space.

**Comment by madoar** [comment]
You often need to look one or two rows below because a few lines (environment variables) are added to the script before execution.

**Comment by Zemogiter** [comment]
I don't know it dosen't look out of place to me.

**Comment by plata** [comment]
Is this fixed by now? If not, any ideas what might be the problem?

**Comment by Zemogiter** [comment]
Cannot test. My Ubuntu installation still loses signal to the monitor before login screen despite me reinstalling it twice. Tried using drivers from nvidia instead of the ones from Additional Drivers tab.

**Comment by plata** [comment]
The problem is: This is marked for alpha 3. So in a way it's blocking us.

**Comment by Zemogiter** [comment]
On the latest commit I can no longer reproduce this issue. Consider this fixed.
