### ISSUE TITLE
Install of Office 2013 fails with "file not found"

### ISSUE THREAD

**Issue by spirritus** [PhoenicisOrg/phoenicis#2053]
Debian 10
Phoenix 5.0rc2

Tried to install Office 2013 with image file mounted.
Phoenicis reported "file not found" and an OK button.
If there was a button "show error" or a hint where the error log is I would have gladly supplied one.

`javax.script.ScriptException: Ausführbare Datei setup32.exe nicht gefunden! in <eval> at line number 121 at column number 8
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:477)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:461)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: <eval>:121:8 Ausführbare Datei setup32.exe nicht gefunden!
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:113)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$704$2842$\^eval\_$cu1$restOf.create([engines, wine, shortcuts, wine]:121)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$699$3037A$\^eval\_$cu1$restOf._createShortcut([engines, wine, quick_script, quick_script]:132)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$684$553$\^eval\_$cu1$restOf.go([engines, wine, quick_script, installer_script]:87)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$261$276$\^eval\_.run(<eval>:10)
	at jdk.nashorn.javaadapters.org_phoenicis_scripts_Installer.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$260$\^eval\_$cu1$restOf.:program(<eval>:66)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:655)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:456)
	... 10 more`

**Comment by Zemogiter** [comment]
The error message mentions nashorn but haven't we replaced it with graalvm?

**Comment by madoar** [comment]
@Zemogiter he is using rc2, which still uses nashorn internally.
@spirritus You should try again with the newest version of Phoenicis, rc2 is around half a year old now so there were quite some changes :)

The current master has a rather big bug during script execution because of an update in our script execution engine. I'm currently fixing this bug in our code. Please wait until the bugfix is merged and then give it a test with the current master branch. I'll write a comment here when the bugfix is merged.

**Comment by plata** [comment]
Closed due to inactivity. Feel free to reopen if the issue persists with current master.
