### ISSUE TITLE
Fetch graphics card info and make it available to script

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/phoenicis#2061]
It should be possible, for example, to at least fetch the graphic card manufacturr (intel/nvdia/amd) in order, for example, to set VK_ICD_FILENAME correctly for Vulkan application.

Fetching OpenGL core context version and Vulkan version could also be interesting, simply to test if drivers are installed (in 32 bits and 64 bits).

**Comment by plata** [comment]
This is somewhat related to #1854.

**Comment by ImperatorS79** [comment]
#1854 is more general, but yes.
I see three ways of doing it:
- Use LWJGL to get the rendering infos (advantage: pure java)
- Use glxinfo and vulkaninfo (and call the program fro Java) (advantage: nearly nothing to do)
- Compile a simple C++ test program to check this (**only** advantage: can be compiled in 32 bits and 64 bits to check if the user have installed OpenGL/Vulkan 32 bits drivers and Vulkan 64 bits driver)

**Comment by ImperatorS79** [comment]
I have normally a working LWJGL code, which compiles and execute in js, but I do not know how to check the returned value. Current code (most part are simply copy paste from LWJGL tutorial ^^):
```java
package org.phoenicis.tools.system;

import org.phoenicis.configuration.security.Safe;

import org.lwjgl.*;
import org.lwjgl.glfw.*;
import org.lwjgl.opengl.*;
import org.lwjgl.system.*;
import org.lwjgl.vulkan.*;

import java.nio.*;

import static org.lwjgl.glfw.Callbacks.*;
import static org.lwjgl.glfw.GLFW.*;
import static org.lwjgl.opengl.GL11.*;
import static org.lwjgl.system.MemoryStack.*;
import static org.lwjgl.system.MemoryUtil.*;
import static org.lwjgl.glfw.GLFWVulkan.*;

@Safe
class GraphicsProperties {
    public GraphicsProperties() {
        Vendor = "Unknown";
        OpenGLVersion = "Unsupported";
        VulkanVersion = "Unsupported";
    }

    public String Vendor;
    public String OpenGLVersion;
    public String VulkanVersion;
}

@Safe
// Code from LWJGL tutorial
public class GraphicsPropertiesFetcher {
    private long window;

    private void init() {
        // Setup an error callback. The default implementation
        // will print the error message in System.err.
        GLFWErrorCallback.createPrint(System.err).set();

        // Initialize GLFW. Most GLFW functions will not work before doing this.
        if (!glfwInit())
            throw new IllegalStateException("Unable to initialize GLFW");

        // Configure GLFW
        glfwDefaultWindowHints(); // optional, the current window hints are already the default
        glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE); // the window will stay hidden after creation
        glfwWindowHint(GLFW_RESIZABLE, GLFW_TRUE); // the window will be resizable

        // Create the window
        window = glfwCreateWindow(300, 300, "Hello World!", NULL, NULL);
        if (window == NULL)
            throw new RuntimeException("Failed to create the GLFW window");

        // Setup a key callback. It will be called every time a key is pressed, repeated or released.
        glfwSetKeyCallback(window, (window, key, scancode, action, mods) -> {
            if (key == GLFW_KEY_ESCAPE && action == GLFW_RELEASE)
                glfwSetWindowShouldClose(window, true); // We will detect this in the rendering loop
        });

        // Get the thread stack and push a new frame
        try (MemoryStack stack = stackPush()) {
            IntBuffer pWidth = stack.mallocInt(1); // int*
            IntBuffer pHeight = stack.mallocInt(1); // int*

            // Get the window size passed to glfwCreateWindow
            glfwGetWindowSize(window, pWidth, pHeight);

            // Get the resolution of the primary monitor
            GLFWVidMode vidmode = glfwGetVideoMode(glfwGetPrimaryMonitor());

            // Center the window
            glfwSetWindowPos(
                    window,
                    (vidmode.width() - pWidth.get(0)) / 2,
                    (vidmode.height() - pHeight.get(0)) / 2);
        } // the stack frame is popped automatically
    }

    private void terminate() {
        glfwFreeCallbacks(window);
        glfwDestroyWindow(window);

        glfwTerminate();
        glfwSetErrorCallback(null).free();
    }

    private void FetchVendorOpenGLVersion(GraphicsProperties graphicsProperties) {
        // Make the OpenGL context current
        glfwMakeContextCurrent(window);

        GL.createCapabilities();

        graphicsProperties.Vendor = glGetString(GL_VENDOR);
        graphicsProperties.OpenGLVersion = glGetString(GL_VERSION);

        GL.destroy();
    }

    private void FetchVulkanVersion(GraphicsProperties graphicsProperties) {
        if (!glfwVulkanSupported()) {
            return;
        }

        graphicsProperties.VulkanVersion = String.valueOf(VK.getInstanceVersionSupported());
    }

    public GraphicsProperties GetProperties() {
        GraphicsProperties graphicsProperties = new GraphicsProperties();

        init();

        FetchVendorOpenGLVersion(graphicsProperties);
        FetchVulkanVersion(graphicsProperties);

        terminate();

        return graphicsProperties;
    }
}
```

**Comment by madoar** [comment]
> but I do not know how to check the returned value.

What do you mean?
To make `GraphicsPropertiesFetcher` accessible from the scripts you only need to add a

```java
    @Bean
    public GraphicsPropertiesFetcher graphicsPropertiesFetcher() {
        return new GraphicsPropertiesFetcher();
    }
```

method to `ToolsConfiguration`.

Afterwards you can access the `GraphicsPropertiesFetcher` in your scripts via:

```javascript
const graphicsProperties = Bean("graphicsPropertiesFetcher").GetProperties();
```

**Comment by ImperatorS79** [comment]
And how do I access the content of the structure/class returned ? I tried `graphicsProperties.Vendor`, but it returned undefined.

**Comment by madoar** [comment]
That is exactly how you should do it. If you are unsure if the Java class works as you expect you can also add some debugging code in it, e.g. some `System.out.println(....);` statements. The most likely scenario is that `glGetString(GL_VENDOR)` returns `null` which may be interpreted as `undefined` by JS.

**Comment by ImperatorS79** [comment]
I have the error "no bean 'graphicsPropertiesFetcher' available" :thinking:.

**Comment by madoar** [comment]
Did you add the above mentioned method to `ToolsConfiguration` and recompile Phoenicis afterwards?

**Comment by ImperatorS79** [comment]
Yes, I did. Maybe I have done a spelling error somewhere because it worker some hours ago.

**Comment by ImperatorS79** [comment]
Okay, so the Vendor and GL Version are :
VMware, Inc.
3.1 Mesa 18.2.8

However, in .js I have `undefined ` for the vendor (did not test GL version)

I will also have to do some work on the version to have it in the format 310.

**Comment by madoar** [comment]
You can try adding a `toString` method to `GraphicsProperties` to check whether the object contains the right information. The method would then look like this:

```java
public String toString() {
   return Vendor + " " + OpenGLVersion + " " + VulkanVersion;
}
```

Afterwards you can test the output via:

Java
```java
System.out.println(graphicsProperties.toString());
```

JavaScript
```javascript
print(Bean("graphicsPropertiesFetcher").GetProperties().toString());
```

**Comment by ImperatorS79** [comment]
Seems it works with that method but not by accessing class member directly.

**Comment by madoar** [comment]
Try adding corresponding getter methods to the class to see if this helps, e.g.:

```java
public String getVendor() {
   return this.Vendor;
}
```

**Comment by ImperatorS79** [comment]
I get 
```java
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - TypeError: undefined is not a function
        at <js> :anonymous(Unnamed:18:698-727)
        at <js> go(Unnamed:81:3209-3243)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.ObjectProxyHandler.invoke(HostInteropReflect.java:678)
        at com.sun.proxy.$Proxy43.go(Unknown Source)
        at org.phoenicis.javafx.components.application.skin.ApplicationInformationPanelSkin.lambda$installScript$7(ApplicationInformationPanelSkin.java:237)
        at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
        at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)

Exception in thread "pool-3-thread-4" TypeError: undefined is not a function
        at <js> :anonymous(Unnamed:18:698-727)
        at <js> go(Unnamed:81:3209-3243)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.ObjectProxyHandler.invoke(HostInteropReflect.java:678)
        at com.sun.proxy.$Proxy43.go(Unknown Source)
        at org.phoenicis.javafx.components.application.skin.ApplicationInformationPanelSkin.lambda$installScript$7(ApplicationInformationPanelSkin.java:237)
        at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
        at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
```
when I try to do 
```js
.preInstall(function() {
        const graphicsProperties = Bean("graphicsPropertiesFetcher").GetProperties();
        print(graphicsProperties.getVendor());
        print(graphicsProperties.getOpenGLVersion());
        print(graphicsProperties.getVulkanVersion());
    });
```

**Comment by madoar** [comment]
@Zemogiter can you open a PR with your changes. It is quite hard to help debugging this without knowing how exactly your Java code looks :)

**Comment by ImperatorS79** [comment]
wrong person ^^, but the java code is in one of the comment

**Comment by madoar** [comment]
But 

```javascript
.preInstall(function() {
        const graphicsProperties = Bean("graphicsPropertiesFetcher").GetProperties();
        print(graphicsProperties.toString());
    });
```

is working correctly?

**Comment by ImperatorS79** [comment]
Yes

**Comment by madoar** [comment]
Try recompiling again maybe the additional getter methods are not correctly added to the class...

**Comment by ImperatorS79** [comment]
Maybe it is `this` ? It is not in the `toString` method.

**Comment by ImperatorS79** [comment]
@madoar Could it be that I call the method on the returned object and not in the call directly ?
It is strange that js cannot manage such a simple structure.

**Comment by madoar** [comment]
> Could it be that I call the method on the returned object and not in the call directly ?

What do you mean?

**Comment by ImperatorS79** [comment]
```js
const graphicsProperties = Bean("graphicsPropertiesFetcher").GetProperties();
print(graphicsProperties.getVendor());
```
vs
```js
print(Bean("graphicsPropertiesFetcher").GetProperties().getVendor());
```

**Comment by madoar** [comment]
This should make no difference. There is something going really wrong with the returned object.
Can you try:

```javascript
const graphicsProperties = Bean("graphicsPropertiesFetcher").GetProperties();

print(graphicsProperties);
print(graphicsProperties.getClass());
print(graphicsProperties.getClass().getSimpleName());
```

and tell us the results?

**Comment by ImperatorS79** [comment]
```
Intel Open Source Technology Center 3.0 1.1.0
class org.phoenicis.tools.system.GraphicsProperties
GraphicsProperties
```

**Comment by madoar** [comment]
Can you try:

```javascript
print("Methods:");
graphicsProperties.getClass().getDeclaredMethods().foreach(method => {
   print(method.getName());
});
print("Fields:");
graphicsProperties.getClass().getDeclaredFields().foreach(field => {
   print(field.getName());
});
```

**Comment by ImperatorS79** [comment]
I got:
```js
Methods:
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - TypeError: undefined is not a function
        at <js> :anonymous(Unnamed:19-21:719-836)
        at <js> go(Unnamed:81:3209-3243)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.ObjectProxyHandler.invoke(HostInteropReflect.java:678)
        at com.sun.proxy.$Proxy43.go(Unknown Source)
        at org.phoenicis.javafx.components.application.skin.ApplicationInformationPanelSkin.lambda$installScript$7(ApplicationInformationPanelSkin.java:237)
        at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
        at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)

Exception in thread "pool-3-thread-4" TypeError: undefined is not a function
        at <js> :anonymous(Unnamed:19-21:719-836)
        at <js> go(Unnamed:81:3209-3243)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.ObjectProxyHandler.invoke(HostInteropReflect.java:678)
        at com.sun.proxy.$Proxy43.go(Unknown Source)
        at org.phoenicis.javafx.components.application.skin.ApplicationInformationPanelSkin.lambda$installScript$7(ApplicationInformationPanelSkin.java:237)
        at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
        at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by madoar** [comment]
Can you try `forEach` instead?

**Comment by ImperatorS79** [comment]
```
Methods:
getVendor
getOpenGLVersion
getVulkan
toString
Fields:
Vendor
OpenGLVersion
VulkanVersion
```

**Comment by madoar** [comment]
Then you should be able to access any of these methods and fields from inside JS.
Have you defined `GraphicsProperties` in its own `*.java` file or is it an inner class of `GraphicsProperties`? Can you please move it to its own file.

In addition try using lower-case field names, e.g. `vendor`, `openGLVersion` etc.

**Comment by ImperatorS79** [comment]
OK it works now.

**Comment by madoar** [comment]
What was the reason?

**Comment by ImperatorS79** [comment]
Well separating `GraphicsProperties` and `GraphicsPropertiesFetcher` in two file did the job.
