### ISSUE TITLE
TimeoutException in AppConfigurationInitialisationTest

### ISSUE THREAD

**Issue by Zemogiter** [PhoenicisOrg/phoenicis#2142]
### Expected behavior
Successful compilation
### Actual behavior
Compilation crashes at testing javafx
[terminal log](https://github.com/PhoenicisOrg/phoenicis/files/4002514/terminal.log)
### Steps to reproduce
Download the latest commit and follow the [documentation](https://phoenicisorg.github.io/phoenicis/Developers/build/)
### System information
* software version (git revision) of phoenicis and scripts repositories
https://github.com/PhoenicisOrg/phoenicis/commit/d5863ba8197208ae37f21b3b7236d0262f59b890
https://github.com/PhoenicisOrg/scripts/commit/fa0eacc623d20d53cbe53144cf0a21212fca9f64
* used operating system
Ubuntu 19.10 x64 5.3.0-24-generic
* used Java version
```
openjdk 11.0.5 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.1)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.1, mixed mode, sharing)
```

**Comment by plata** [comment]
This is again our infamous `TimeoutException`... I still have no clue what is causing this on some machines. Use `-DskipTests` as workaround.

**Comment by qparis** [comment]
> This is again our infamous `TimeoutException`... I still have no clue what is causing this on some machines. Use `-DskipTests` as workaround.

Same problem. Can we ignore the test until we fix it?

**Comment by plata** [comment]
@qparis actually I don't even know what the test does. I think you wrote it, didn't you?

**Comment by qparis** [comment]
Hmm no I don’t remember having written this test

**Comment by Zemogiter** [comment]
What does
```
catch (TimeoutException e) {
            e.printStackTrace();
            fail();
        }
```
do in `phoenicis-javafx/src/test/java/org/phoenicis/javafx/AppConfigurationInitialisationTest.java`? Maybe this is causing the issue.

**Comment by plata** [comment]
Oh, just checked the history. It has been created by @madoar. @madoar do we need this test?

**Comment by madoar** [comment]
@plata to run the application we don't need the test, but it is the only test we have that checks whether the application (the JavaFX UI) can be started at all. If such a test is not that important or if we replace the test by some other kind of test I'm fine with removing it.

**Comment by plata** [comment]
Right now it seems to be causing more issues than it solves. I would like to have the test but if we cannot make it run properly, it's probably better to remove it. Do you have an idea what the problem might be?

**Comment by Zemogiter** [comment]
Latest commit compilation results in error:
```
[INFO] -------------------< org.phoenicis:phoenicis-javafx >-------------------
[INFO] Building phoenicis-javafx 5.0-SNAPSHOT                           [13/16]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ phoenicis-javafx ---
[INFO] 
[INFO] --- sortpom-maven-plugin:2.10.0:sort (default) @ phoenicis-javafx ---
[INFO] Sorting file /home/jonasz/Pobrane/phoenicis-master/phoenicis-javafx/pom.xml
[INFO] Pom file is already sorted, exiting
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ phoenicis-javafx ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (agent) @ phoenicis-javafx ---
[INFO] argLine set to -javaagent:/home/jonasz/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/jonasz/Pobrane/phoenicis-master/phoenicis-javafx/target/jacoco.exec,excludes=**/org/phoenicis/javafx/**:**/org/phoenicis/app/**
[INFO] 
[INFO] --- lesscss-maven-plugin:1.2.1:compile (default) @ phoenicis-javafx ---
[INFO] Compiling 10 sources to /home/jonasz/Pobrane/phoenicis-master/phoenicis-javafx/target/classes
[INFO] Finished sources compilation in 842 milliseconds
[INFO] 
[INFO] --- formatter-maven-plugin:2.11.0:format (default) @ phoenicis-javafx ---
[INFO] Using 'UTF-8' encoding to format source files.
[INFO] Number of files to be formatted: 192
[INFO] Successfully formatted:          0 file(s)
[INFO] Fail to format:                  0 file(s)
[INFO] Skipped:                         192 file(s)
[INFO] Read only skipped:               0 file(s)
[INFO] Approximate time taken:          0s
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ phoenicis-javafx ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 121 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ phoenicis-javafx ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 191 source files to /home/jonasz/Pobrane/phoenicis-master/phoenicis-javafx/target/classes
[INFO] /home/jonasz/Pobrane/phoenicis-master/phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/common/skin/SidebarToggleGroupBaseSkin.java: Some input files use unchecked or unsafe operations.
[INFO] /home/jonasz/Pobrane/phoenicis-master/phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/common/skin/SidebarToggleGroupBaseSkin.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ phoenicis-javafx ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ phoenicis-javafx ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/jonasz/Pobrane/phoenicis-master/phoenicis-javafx/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M4:test (default-test) @ phoenicis-javafx ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.phoenicis.javafx.AppConfigurationInitialisationTest
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.testfx.util.WaitForAsyncUtils$ASyncFXCallable.get(WaitForAsyncUtils.java:715)
	at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:298)
	at org.testfx.api.FxToolkit.waitForSetup(FxToolkit.java:245)
	at org.testfx.api.FxToolkit.setupFixture(FxToolkit.java:202)
	at org.phoenicis.javafx.AppConfigurationInitialisationTest.testAppConfigurationInitialisation(AppConfigurationInitialisationTest.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 30.24 s <<< FAILURE! - in org.phoenicis.javafx.AppConfigurationInitialisationTest
[ERROR] org.phoenicis.javafx.AppConfigurationInitialisationTest.testAppConfigurationInitialisation  Time elapsed: 30.2 s  <<< FAILURE!
java.lang.AssertionError
	at org.phoenicis.javafx.AppConfigurationInitialisationTest.testAppConfigurationInitialisation(AppConfigurationInitialisationTest.java:52)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   AppConfigurationInitialisationTest.testAppConfigurationInitialisation:52
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for phoenicis 5.0-SNAPSHOT:
[INFO] 
[INFO] phoenicis .......................................... SUCCESS [  0.987 s]
[INFO] phoenicis-configuration ............................ SUCCESS [  5.928 s]
[INFO] phoenicis-entities ................................. SUCCESS [  0.725 s]
[INFO] phoenicis-multithreading ........................... SUCCESS [  1.116 s]
[INFO] phoenicis-win32 .................................... SUCCESS [  1.081 s]
[INFO] phoenicis-tools .................................... SUCCESS [  4.969 s]
[INFO] phoenicis-repository ............................... SUCCESS [  1.865 s]
[INFO] phoenicis-scripts .................................. SUCCESS [  0.368 s]
[INFO] phoenicis-library .................................. SUCCESS [  0.200 s]
[INFO] phoenicis-engines .................................. SUCCESS [  0.215 s]
[INFO] phoenicis-settings ................................. SUCCESS [  0.127 s]
[INFO] phoenicis-containers ............................... SUCCESS [  0.172 s]
[INFO] phoenicis-javafx ................................... FAILURE [ 33.841 s]
[INFO] phoenicis-cli ...................................... SKIPPED
[INFO] phoenicis-dist ..................................... SKIPPED
[INFO] phoenicis-tests .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  51.785 s
[INFO] Finished at: 2019-12-29T12:55:44+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-test) on project phoenicis-javafx: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/jonasz/Pobrane/phoenicis-master/phoenicis-javafx/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :phoenicis-javafx
```

**Comment by madoar** [comment]
@plata for now I agree let us either remove the test or set it to ignored. The problem is that we don't know what leads to the timeout. My guess is that it is either a thread pool issue or some kind of I/O issue (maybe the UI triggers an update of the wine version list that hangs?)

**Comment by plata** [comment]
I have no clue what's causing the issue. Can you open a PR with whatever solution you prefer?

**Comment by plata** [comment]
Would it be possible to write the test more in the way of https://github.com/TestFX/TestFX/wiki/Getting-Started?

**Comment by madoar** [comment]
Yes this is basically the goal. For now I think it is more important to get it building with the least amount of effort. For now I think we should simply [ignore](http://junit.sourceforge.net/javadoc/org/junit/Ignore.html) the test or remove it completely. Most likely I will not be able to do this today.

**Comment by Zemogiter** [comment]
Closed by #2148

**Comment by plata** [comment]
I didn't close this on purpose. The issue is not really solved. We just do not run the test currently.
