### ISSUE TITLE
Syntax error: unexpected end of input

### ISSUE THREAD

**Issue by Zemogiter** [PhoenicisOrg/phoenicis#2172]
### Expected behavior
The application starts
### Actual behavior
Clicking on the play button results in this error:
```
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - SyntaxError: Unexpected end of input
	at <js> _installRuntime(Unnamed:160:6217-6246)
	at <js> install(Unnamed:48:2193-2230)
	at <js> run(Unnamed:381:14282-14315)
	at <js> run(Unnamed:172:5961-6051)
	at <js> run(Unnamed:39-41:1236-1400)
	at <js> run(Unnamed:107:3187-3216)
	at com.oracle.truffle.polyglot.ObjectProxyHandler.invoke(HostInteropReflect.java:678)
	at com.sun.proxy.$Proxy65.run(Unknown Source)
	at org.phoenicis.library.ShortcutRunner.lambda$run$0(ShortcutRunner.java:52)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

[WARNING] 
org.graalvm.polyglot.PolyglotException: SyntaxError: Unexpected end of input
    at <js>._installRuntime (Unnamed:160)
    at <js>.install (Unnamed:48)
    at <js>.run (Unnamed:381)
    at <js>.run (Unnamed:172)
    at <js>.run (Unnamed:39)
    at <js>.run (Unnamed:107)
    at com.oracle.truffle.polyglot.ObjectProxyHandler.invoke (HostInteropReflect.java:678)
    at com.sun.proxy.$Proxy65.run (Unknown Source)
    at org.phoenicis.library.ShortcutRunner.lambda$run$0 (ShortcutRunner.java:52)
    at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval (PhoenicisInteractiveScriptSession.java:35)
    at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1 (BackgroundScriptInterpreter.java:45)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)

```
Also occurs when using the "Run executable" button. Tried compiling POL5 with java 13 and the error remains.
### Steps to reproduce
Pull the latest master of both repos, compile it and use `mvn install` inside `phoenicis-javafx`
### System information
* software version (git revision) of phoenicis and scripts repositories
https://github.com/PhoenicisOrg/phoenicis/commit/19a9ab4548b5c523662147e64c84b873a5d1a1e6
https://github.com/PhoenicisOrg/scripts/commit/c8904dcbddaa6bc1ff44a20027ae45c776531456
* used operating system
Ubuntu 19.04 x64 5.3.0-26-generic
* used Java version
```
openjdk 11.0.5 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.1)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.1, mixed mode, sharing)
```

**Comment by plata** [comment]
I'm not sure if the output is 100% correct but the issue seems to be somewhere around https://github.com/PhoenicisOrg/scripts/blob/c8904dcbddaa6bc1ff44a20027ae45c776531456/Engines/Wine/Engine/Implementation/script.js#L159. Can you add some print outs to figure out where exactly it happens?

**Comment by Zemogiter** [comment]
`print ("oldRuntimeJsonFile: " + oldRuntimeJsonFile);` retruns blank while `print ("oldRuntimeJson: " + oldRuntimeJson);` dosen't show anything in terminal

**Comment by plata** [comment]
Can you print `runtimeJsonPath` before 
```Javascript
if (!fileExists(runtimeJsonPath)) {
```
?
Is `this._wineEnginesDirectory` set correctly in https://github.com/PhoenicisOrg/scripts/blob/c8904dcbddaa6bc1ff44a20027ae45c776531456/Engines/Wine/Engine/Implementation/script.js#L24?

Apart from that it should be
```
const oldRuntimeJsonFile = cat(runtimeJsonPath);
const oldRuntimeJson = JSON.parse(oldRuntimeJsonFile);
```

**Comment by Zemogiter** [comment]
@plata here is the terminal output after adding `print ("runtimeJsonPath: " + runtimeJsonPath);` right above that `if` and changing `const oldRuntimeJsonFile = cat(this._wineEnginesDirectory + "/runtime.json");` to `const oldRuntimeJsonFile = cat(runtimeJsonPath);`:

```
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
[INFO ] org.phoenicis.repository.DefaultRepositoryManager (l.133) - Adding repositories: [org.phoenicis.repository.location.LocalRepositoryLocation@5ba4609d[/home/jonasz/Pobrane/scripts-master]] at index 0
[INFO ] org.phoenicis.repository.types.MultipleRepository (l.46) - Fetching applications for: org.phoenicis.repository.types.MultipleRepository@6072176b[repositories=[org.phoenicis.repository.types.LocalRepository@6eb5e515[repositorySource=file:/home/jonasz/Pobrane/scripts-master/,repositoryDirectory=/home/jonasz/Pobrane/scripts-master]]]
[INFO ] org.phoenicis.repository.types.LocalRepository (l.77) - Reading directory : /home/jonasz/Pobrane/scripts-master
[INFO ] org.phoenicis.repository.types.MultipleRepository (l.46) - Fetching applications for: org.phoenicis.repository.types.MultipleRepository@6072176b[repositories=[org.phoenicis.repository.types.LocalRepository@6eb5e515[repositorySource=file:/home/jonasz/Pobrane/scripts-master/,repositoryDirectory=/home/jonasz/Pobrane/scripts-master]]]
[INFO ] org.phoenicis.repository.types.LocalRepository (l.77) - Reading directory : /home/jonasz/Pobrane/scripts-master
[INFO ] org.phoenicis.repository.types.MultipleRepository (l.46) - Fetching applications for: org.phoenicis.repository.types.MultipleRepository@6072176b[repositories=[org.phoenicis.repository.types.LocalRepository@6eb5e515[repositorySource=file:/home/jonasz/Pobrane/scripts-master/,repositoryDirectory=/home/jonasz/Pobrane/scripts-master]]]
[INFO ] org.phoenicis.repository.types.LocalRepository (l.77) - Reading directory : /home/jonasz/Pobrane/scripts-master
runtimeJsonPath: /home/jonasz/.Phoenicis/engines//wine/runtime.json
oldRuntimeJsonFile: 
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - SyntaxError: Unexpected end of input
	at <js> _installRuntime(Unnamed:162:6308-6337)
	at <js> install(Unnamed:48:2193-2230)
	at <js> run(Unnamed:386:14540-14573)
	at <js> run(Unnamed:172:5961-6051)
	at <js> run(Unnamed:39-41:1236-1400)
	at <js> run(Unnamed:107:3187-3216)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.ObjectProxyHandler.invoke(HostInteropReflect.java:678)
	at com.sun.proxy.$Proxy47.run(Unknown Source)
	at org.phoenicis.library.ShortcutRunner.lambda$run$0(ShortcutRunner.java:52)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

Exception in thread "pool-4-thread-4" SyntaxError: Unexpected end of input
	at <js> _installRuntime(Unnamed:162:6308-6337)
	at <js> install(Unnamed:48:2193-2230)
	at <js> run(Unnamed:386:14540-14573)
	at <js> run(Unnamed:172:5961-6051)
	at <js> run(Unnamed:39-41:1236-1400)
	at <js> run(Unnamed:107:3187-3216)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.ObjectProxyHandler.invoke(HostInteropReflect.java:678)
	at com.sun.proxy.$Proxy47.run(Unknown Source)
	at org.phoenicis.library.ShortcutRunner.lambda$run$0(ShortcutRunner.java:52)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
```
That .json file in `runtimeJsonPath` is blank.

**Comment by plata** [comment]
Could it be that you aborted an installation because downloading the versions json took forever? In this case the file can be empty. We should enhance the check such that it doesn't only test if the file exists but also if it's not empty. Or even better that it's a valid json file.

**Comment by Zemogiter** [comment]
I don't think I've cancelled the app installation at that stage.

**Comment by plata** [comment]
Could you implement the fix I've mentioned before nevertheless?
