### ISSUE TITLE
Package creation failiure...again

### ISSUE THREAD

**Issue by Zemogiter** [PhoenicisOrg/phoenicis#2214]
### Expected behavior
The deb package is correct size.
### Actual behavior
`Phoenicis_5.0-SNAPSHOT.deb` is 73,6 kilobytes. And I get this error:
```
jonasz@jonasz-Z270-Gaming-K3:~/Pobrane/phoenicis-master/phoenicis-dist/src/scripts$ bash phoenicis-create-package.sh
Warning: Version not specified. Reading from pom.xml
Using 5.0-SNAPSHOT
--2020-05-09 13:26:32--  http://download2.gluonhq.com/jpackager/11/jdk.packager-linux.zip
Translacja download2.gluonhq.com (download2.gluonhq.com)... 178.128.135.159
Łączenie się z download2.gluonhq.com (download2.gluonhq.com)|178.128.135.159|:80... połączono.
Żądanie HTTP wysłano, oczekiwanie na odpowiedź... 200 OK
Długość: 674385 (659K) [application/zip]
Zapis do: `jdk.packager-linux.zip'

jdk.packager-linux. 100%[===================>] 658,58K   397KB/s    w 1,7s     

2020-05-09 13:26:34 (397 KB/s) - zapisano `jdk.packager-linux.zip' [674385/674385]

Archive:  jdk.packager-linux.zip
  inflating: jdk.packager.jar        
  inflating: jpackager               
WARNING: package jdk.tools.jlink.internal.packager not in jdk.jlink
WARNING: argument [linux-bundle-name] is not supported for current configuration.
Creating app bundle: /home/jonasz/Pobrane/phoenicis-master/phoenicis-dist/src/scripts/../../target/packages/PhoenicisPlayOnLinux
Exception in thread "main" java.lang.NoClassDefFoundError: jdk/tools/jlink/internal/packager/AppRuntimeImageBuilder
	at jdk.packager/jdk.packager.internal.RedistributableModules.getRedistributableModules(RedistributableModules.java:74)
	at jdk.packager/jdk.packager.internal.JLinkBundlerHelper$ModuleHelper.<init>(JLinkBundlerHelper.java:526)
	at jdk.packager/jdk.packager.internal.JLinkBundlerHelper.getRedistributableModules(JLinkBundlerHelper.java:261)
	at jdk.packager/jdk.packager.internal.JLinkBundlerHelper.execute(JLinkBundlerHelper.java:312)
	at jdk.packager/jdk.packager.internal.linux.LinuxAppBundler.doAppBundle(LinuxAppBundler.java:249)
	at jdk.packager/jdk.packager.internal.linux.LinuxAppBundler.doBundle(LinuxAppBundler.java:214)
	at jdk.packager/jdk.packager.internal.linux.LinuxAppBundler.execute(LinuxAppBundler.java:344)
	at jdk.packager/jdk.packager.internal.Arguments.generateBundle(Arguments.java:638)
	at jdk.packager/jdk.packager.internal.Arguments.processArguments(Arguments.java:582)
	at jdk.packager/jdk.packager.Main.run(Main.java:71)
	at jdk.packager/jdk.packager.Main.main(Main.java:47)
Caused by: java.lang.ClassNotFoundException: jdk.tools.jlink.internal.packager.AppRuntimeImageBuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 11 more
```
### Steps to reproduce
- install openjdk14 and openjre14
- write `export JAVA_HOME=/usr/lib/jvm/java-14-openjdk-amd64` in terminal then `mvn clear package` then `cd phoenicis-dist/src/scripts` then `bash phoenicis-create-package.sh`
### System information
* software version (git revision) of phoenicis and scripts repositories
https://github.com/PhoenicisOrg/phoenicis/commit/b523e3f9e250fa2fee3ae24d2e6236b72125c9d3
* used operating system
Ubuntu 20.04
* used Java version
```
openjdk 14.0.1 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7-Ubuntu-1ubuntu1)
OpenJDK 64-Bit Server VM (build 14.0.1+7-Ubuntu-1ubuntu1, mixed mode, sharing
```

**Comment by plata** [comment]
Do you have the error also with JDK 11 - 13?

**Comment by Zemogiter** [comment]
Switching to JDK 13 produces a slighty different error message:
```
Warning: Version not specified. Reading from pom.xml
Using 5.0-SNAPSHOT
--2020-05-10 11:52:08--  http://download2.gluonhq.com/jpackager/11/jdk.packager-linux.zip
Translacja download2.gluonhq.com (download2.gluonhq.com)... 178.128.135.159
Łączenie się z download2.gluonhq.com (download2.gluonhq.com)|178.128.135.159|:80... połączono.
Żądanie HTTP wysłano, oczekiwanie na odpowiedź... 200 OK
Długość: 674385 (659K) [application/zip]
Zapis do: `jdk.packager-linux.zip'

jdk.packager-linux. 100%[===================>] 658,58K   865KB/s    w 0,8s     

2020-05-10 11:52:09 (865 KB/s) - zapisano `jdk.packager-linux.zip' [674385/674385]

Archive:  jdk.packager-linux.zip
  inflating: jdk.packager.jar        
  inflating: jpackager               
WARNING: argument [linux-bundle-name] is not supported for current configuration.
Creating app bundle: /home/jonasz/Pobrane/phoenicis-master/phoenicis-dist/src/scripts/../../target/packages/PhoenicisPlayOnLinux
Module org.graalvm.truffle does not exist.
Module javafx.web does not exist.
Module javafx.base does not exist.
Module javafx.graphics does not exist.
Module javafx.controls does not exist.
Module javafx.media does not exist.
"Adding modules: [jdk.crypto.ec, java.base, javafx.base, javafx.web, javafx.media, javafx.graphics, javafx.controls, java.naming, java.sql, java.scripting, jdk.internal.vm.ci, org.graalvm.truffle, java.management] to runtime image."
Exception: jdk.tools.jlink.plugin.PluginException: java.lang.module.FindException: Hash of java.xml (f1f657aea12b4a48e40256643ff2468f4b222fa2068d62959c6f6c9666b0882e) differs to expected hash (aee2540f9cc903085367c06f6d7e436de256969c20c49fe6e9a839640f068308) recorded in java.base
Error: Bundler "Linux Application Image" (linux.app) failed to produce a bundle.
```

**Comment by plata** [comment]
Like java.xml is from a different jdk than java.base...

**Comment by madoar** [comment]
JDK 14 comes with a builtin jpackager called `jpackage`, see https://openjdk.java.net/jeps/343. Therefore the whole script needs to be removed/replaced if used with Java 14.

**Comment by Zemogiter** [comment]
After the latest commit I get a different error:
```
bash phoenicis-create-package.sh
Warning: Version not specified. Reading from pom.xml
Using 5.0-SNAPSHOT
--2020-06-16 15:34:22--  http://download2.gluonhq.com/jpackager/11/jdk.packager-linux.zip
Translacja download2.gluonhq.com (download2.gluonhq.com)... 178.128.135.159
Łączenie się z download2.gluonhq.com (download2.gluonhq.com)|178.128.135.159|:80... połączono.
Żądanie HTTP wysłano, oczekiwanie na odpowiedź... 200 OK
Długość: 674385 (659K) [application/zip]
Zapis do: `jdk.packager-linux.zip'

jdk.packager-linux. 100%[===================>] 658,58K   622KB/s    w 1,1s     

2020-06-16 15:34:24 (622 KB/s) - zapisano `jdk.packager-linux.zip' [674385/674385]

Archive:  jdk.packager-linux.zip
  inflating: jdk.packager.jar        
  inflating: jpackager               
WARNING: package jdk.tools.jlink.internal.packager not in jdk.jlink
WARNING: argument [linux-bundle-name] is not supported for current configuration.
Creating app bundle: /home/jonasz/Pobrane/phoenicis-master/phoenicis-dist/src/scripts/../../target/packages/PhoenicisPlayOnLinux
Exception in thread "main" java.lang.NoClassDefFoundError: jdk/tools/jlink/internal/packager/AppRuntimeImageBuilder
	at jdk.packager/jdk.packager.internal.RedistributableModules.getRedistributableModules(RedistributableModules.java:74)
	at jdk.packager/jdk.packager.internal.JLinkBundlerHelper$ModuleHelper.<init>(JLinkBundlerHelper.java:526)
	at jdk.packager/jdk.packager.internal.JLinkBundlerHelper.getRedistributableModules(JLinkBundlerHelper.java:261)
	at jdk.packager/jdk.packager.internal.JLinkBundlerHelper.execute(JLinkBundlerHelper.java:312)
	at jdk.packager/jdk.packager.internal.linux.LinuxAppBundler.doAppBundle(LinuxAppBundler.java:249)
	at jdk.packager/jdk.packager.internal.linux.LinuxAppBundler.doBundle(LinuxAppBundler.java:214)
	at jdk.packager/jdk.packager.internal.linux.LinuxAppBundler.execute(LinuxAppBundler.java:344)
	at jdk.packager/jdk.packager.internal.Arguments.generateBundle(Arguments.java:638)
	at jdk.packager/jdk.packager.internal.Arguments.processArguments(Arguments.java:582)
	at jdk.packager/jdk.packager.Main.run(Main.java:71)
	at jdk.packager/jdk.packager.Main.main(Main.java:47)
Caused by: java.lang.ClassNotFoundException: jdk.tools.jlink.internal.packager.AppRuntimeImageBuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 11 more
```
Using jdk 14

**Comment by plata** [comment]
Did you see https://github.com/PhoenicisOrg/phoenicis/pull/2227?

**Comment by Zemogiter** [comment]
Yeah just now
