### ISSUE TITLE
Screen hangs on "Loading Available Wine-Versions"

### ISSUE THREAD

**Issue by erdincay** [PhoenicisOrg/phoenicis#2306]
### Expected behavior

**show the available wine versions**

### Actual behavior

**screen hangs on loading the wine versions**

### Steps to reproduce

- install playonlinux5 from pop-os shop as flatpak
- start phoenicis-playonlinux5 from the application listings
- select apps > local installer
- add a name to create a local installer
- select next

### System information

- PopOS - Ubuntu 
- git is not needed in this constellation
- openjdk 11.0.9.1 2020-11-04
- OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
- OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
- javac 1.8.0_275

**Comment by erdincay** [comment]
please also have a look at this issue with playonlinux4: https://www.reddit.com/r/wine_gaming/comments/klo9al/playonlinux_434_issues_with_pango_cairo_python/

**Comment by qparis** [comment]
Hi! 
Thank you for having reported the problem. I think it was a problem regarding the IPv6 configuration of one subdomain. It should be fixed in ~5 minutes

**Comment by erdincay** [comment]
thank you @qparis, do you have any ideas, how i can fix this issue: 

PlayOnLinux version: 4.3.4, Python version: 2.7.18:

This is the error message, that I receive when starting PlayOnLinux:Looking for python... 2.7.18 - wxversion(s): 3.0-gtk3selected1**Pango:ERROR:../pango/pangofc-fontmap.c:1408:pango_fc_font_map_list_families: assertion failed: (res == FcResultMatch)Bail out! Pango:ERROR:../pango/pangofc-fontmap.c:1408:pango_fc_font_map_list_families: assertion failed: (res == FcResultMatch)/usr/share/playonlinux/playonlinux: Zeile 126: 546008 Abgebrochen (Speicherabzug geschrieben) "$POL_PYTHON" mainwindow.py "$@"

I already did an clean reinstall:

sudo apt purge -y playonlinux && sudo apt autoremove -y
sudo apt install playonlinux

Best regards.

**Comment by plata** [comment]
Can we separate the different issues? As the original problem is solved, I would like to close this. Also, the new issue is PoL 4 so this should not be discussed in this repository.

**Comment by erdincay** [comment]
> Can we separate the different issues? As the original problem is solved, I would like to close this. Also, the new issue is PoL 4 so this should not be discussed in this repository.

OK, is it deployed already, tell me how to test it properly, because my installed version did not change, and is still slow.

**Comment by frknkrc44** [comment]
I have some log about this issue:

```
$ flatpak run org.phoenicis.playonlinux
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
[INFO ] org.phoenicis.repository.DefaultRepositoryManager (l.133) - Adding repositories: [org.phoenicis.repository.location.GitRepositoryLocation@56c90f63[https://github.com/PhoenicisOrg/scripts,release/5.0-alpha-3], org.phoenicis.repository.location.ClasspathRepositoryLocation@75cb91b3[/org/phoenicis/repository]] at index 0
[INFO ] org.phoenicis.repository.types.MultipleRepository (l.46) - Fetching applications for: org.phoenicis.repository.types.MultipleRepository@28defb5e[repositories=[GitRepository(url: 'https://github.com/PhoenicisOrg/scripts', folder: '/home/diana/.Phoenicis/cache/git-298283779', branch: 'release/5.0-alpha-3'), org.phoenicis.repository.types.ClasspathRepository@26190035[packagePath=/org/phoenicis/repository]]]
[INFO ] org.phoenicis.repository.types.GitRepository (l.72) - Begin fetching process of 'https://github.com/PhoenicisOrg/scripts' to '/home/diana/.Phoenicis/cache/git-298283779'
[INFO ] org.phoenicis.repository.types.GitRepository (l.135) - Opening git-repository at '/home/diana/.Phoenicis/cache/git-298283779'
[INFO ] org.phoenicis.repository.types.GitRepository (l.141) - Pulling new commits to '/home/diana/.Phoenicis/cache/git-298283779'
[INFO ] org.phoenicis.repository.types.GitRepository (l.145) - Finished pulling new commits to '/home/diana/.Phoenicis/cache/git-298283779'
[INFO ] org.phoenicis.repository.types.LocalRepository (l.77) - Reading directory : /home/diana/.Phoenicis/cache/git-298283779
[Use -Dgraal.LogFile=<path> to redirect Graal log output to a file.]
Cannot install GraalVM MBean due to Receiver class org.graalvm.compiler.hotspot.management.HotSpotGraalManagement does not define or inherit an implementation of the resolved method 'abstract void initialize(org.graalvm.compiler.hotspot.HotSpotGraalRuntime, org.graalvm.compiler.hotspot.GraalHotSpotVMConfig)' of interface org.graalvm.compiler.hotspot.HotSpotGraalManagementRegistration.
Şub 24, 2021 4:50:43 ÖÖ com.sun.javafx.css.StyleManager$ImageCache getCachedImage
WARNING: Error loading image: file:/home/diana/.Phoenicis/cache/git-298283779/Applications/Games/Total%20War%20Rome%20II/miniatures/main.png
[WARN ] org.phoenicis.javafx.views.mainwindow.installations.dto.InstallationDTO (l.56) - Installation ID (Microsoft Office 2013_1614131452332) contains invalid characters, will remove them.
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - Download of https://phoenicis.playonlinux.com/index.php/wine?os=linux has failed
        at phoenicis.tools@5.0-alpha-3/org.phoenicis.tools.http.Downloader.get(Downloader.java:265)
        at phoenicis.tools@5.0-alpha-3/org.phoenicis.tools.http.Downloader.get(Downloader.java:239)
        at phoenicis.tools@5.0-alpha-3/org.phoenicis.tools.http.Downloader.get(Downloader.java:101)
        at phoenicis.tools@5.0-alpha-3/org.phoenicis.tools.http.Downloader.get(Downloader.java:81)
        at <js> get(Unnamed:135-144:3540-3841)
        at <js> module.getAvailableVersions(Unnamed:108-114:3822-4031)
        at <js> getLatestVersion(Unnamed:81:2912-2946)
        at <js> module.getLatestStagingVersion(Unnamed:133:4606-4684)
        at <js> _determineWineVersion(Unnamed:157:4225-4281)
        at <js> go(Unnamed:26:888-926)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.ObjectProxyHandler.invoke(HostInteropReflect.java:694)
        at com.sun.proxy.$Proxy59.go(Unknown Source)
        at phoenicis.javafx@5.0-alpha-3/org.phoenicis.javafx.components.application.skin.ApplicationInformationPanelSkin.lambda$installScript$7(ApplicationInformationPanelSkin.java:271)
        at phoenicis.scripts@5.0-alpha-3/org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
        at phoenicis.scripts@5.0-alpha-3/org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by host exception: org.phoenicis.tools.http.DownloadException: Download of https://phoenicis.playonlinux.com/index.php/wine?os=linux has failed

Exception in thread "pool-4-thread-2" Download of https://phoenicis.playonlinux.com/index.php/wine?os=linux has failed
        at phoenicis.tools@5.0-alpha-3/org.phoenicis.tools.http.Downloader.get(Downloader.java:265)
        at phoenicis.tools@5.0-alpha-3/org.phoenicis.tools.http.Downloader.get(Downloader.java:239)
        at phoenicis.tools@5.0-alpha-3/org.phoenicis.tools.http.Downloader.get(Downloader.java:101)
        at phoenicis.tools@5.0-alpha-3/org.phoenicis.tools.http.Downloader.get(Downloader.java:81)
        at <js> get(Unnamed:135-144:3540-3841)
        at <js> module.getAvailableVersions(Unnamed:108-114:3822-4031)
        at <js> getLatestVersion(Unnamed:81:2912-2946)
        at <js> module.getLatestStagingVersion(Unnamed:133:4606-4684)
        at <js> _determineWineVersion(Unnamed:157:4225-4281)
        at <js> go(Unnamed:26:888-926)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.ObjectProxyHandler.invoke(HostInteropReflect.java:694)
        at com.sun.proxy.$Proxy59.go(Unknown Source)
        at phoenicis.javafx@5.0-alpha-3/org.phoenicis.javafx.components.application.skin.ApplicationInformationPanelSkin.lambda$installScript$7(ApplicationInformationPanelSkin.java:271)
        at phoenicis.scripts@5.0-alpha-3/org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
        at phoenicis.scripts@5.0-alpha-3/org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by host exception: org.phoenicis.tools.http.DownloadException: Download of https://phoenicis.playonlinux.com/index.php/wine?os=linux has failed
```

**Comment by plata** [comment]
When this happen, can you access https://phoenicis.playonlinux.com/index.php/wine?os=linux in your browser?

**Comment by frknkrc44** [comment]
> When this happen, can you access https://phoenicis.playonlinux.com/index.php/wine?os=linux in your browser?

yes I did @plata

**Comment by plata** [comment]
Strange. I cannot imagine why your browser can access the URL but not Phoenicis. Unless you have a proxy. Or is there a difference in/outside flatpak?
