### ISSUE TITLE
Not able to create a shortcut to a file outside of the wineprefix

### ISSUE THREAD

**Issue by razzeee** [PhoenicisOrg/phoenicis#2353]
### Expected behavior
Being able to create a shortcut to a file in my download folder that's outside of a wineprefix.

### Actual behavior
Shows an error
![image](https://user-images.githubusercontent.com/5943908/105739421-614a5200-5f38-11eb-999b-d5eb348f3576.png)

### Steps to reproduce
- Advanced mode
- Create shortcut
- Insert this
![image](https://user-images.githubusercontent.com/5943908/105739092-087ab980-5f38-11eb-85e1-eb7eae7b94ac.png)
- Try to run this file https://supportportal.gemalto.com/csm?id=kb_article_view&sys_kb_id=f5e5df901b802c50f12064606e4bcb18&sysparm_article=KB0023073

### System information
* software version (git revision) of phoenicis and scripts repositories -> current flatpak
* used operating system -> Fedora 33

### Log

```
flatpak run org.phoenicis.playonlinux 
Gtk-Message: 18:02:33.847: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:02:33.848: Failed to load module "pk-gtk-module"
Gtk-Message: 18:02:33.848: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:02:33.848: Failed to load module "pk-gtk-module"
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
[INFO ] org.phoenicis.repository.DefaultRepositoryManager (l.133) - Adding repositories: [org.phoenicis.repository.location.GitRepositoryLocation@57f4aaca[https://github.com/PhoenicisOrg/scripts,release/5.0-alpha-3], org.phoenicis.repository.location.ClasspathRepositoryLocation@6fbe4652[/org/phoenicis/repository]] at index 0
Jan 25, 2021 6:02:38 PM com.sun.javafx.css.StyleManager$ImageCache getCachedImage
WARNING: Error loading image: file:/home/klampe/.Phoenicis/shortcuts/MobilePass.miniature
Jan 25, 2021 6:02:39 PM com.sun.javafx.css.StyleManager$ImageCache getCachedImage
WARNING: Error loading image: file:/home/klampe/.Phoenicis/shortcuts/MobilePass.miniature
[Use -Dgraal.LogFile=<path> to redirect Graal log output to a file.]
Cannot install GraalVM MBean due to Receiver class org.graalvm.compiler.hotspot.management.HotSpotGraalManagement does not define or inherit an implementation of the resolved method 'abstract void initialize(org.graalvm.compiler.hotspot.HotSpotGraalRuntime, org.graalvm.compiler.hotspot.GraalHotSpotVMConfig)' of interface org.graalvm.compiler.hotspot.HotSpotGraalManagementRegistration.
[INFO ] org.phoenicis.repository.types.MultipleRepository (l.46) - Fetching applications for: org.phoenicis.repository.types.MultipleRepository@42feb1bb[repositories=[GitRepository(url: 'https://github.com/PhoenicisOrg/scripts', folder: '/home/klampe/.Phoenicis/cache/git-298283779', branch: 'release/5.0-alpha-3'), org.phoenicis.repository.types.ClasspathRepository@58be7d27[packagePath=/org/phoenicis/repository]]]
[INFO ] org.phoenicis.repository.types.GitRepository (l.72) - Begin fetching process of 'https://github.com/PhoenicisOrg/scripts' to '/home/klampe/.Phoenicis/cache/git-298283779'
[INFO ] org.phoenicis.repository.types.GitRepository (l.135) - Opening git-repository at '/home/klampe/.Phoenicis/cache/git-298283779'
[INFO ] org.phoenicis.repository.types.GitRepository (l.141) - Pulling new commits to '/home/klampe/.Phoenicis/cache/git-298283779'
[INFO ] org.phoenicis.repository.types.GitRepository (l.145) - Finished pulling new commits to '/home/klampe/.Phoenicis/cache/git-298283779'
[INFO ] org.phoenicis.repository.types.LocalRepository (l.77) - Reading directory : /home/klampe/.Phoenicis/cache/git-298283779
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - java.lang.ClassCastException: class java.lang.String cannot be cast to class org.graalvm.polyglot.Value (java.lang.String is in module java.base of loader 'bootstrap'; org.graalvm.polyglot.Value is in module org.graalvm.sdk of loader 'app')
	at phoenicis.javafx@5.0-alpha-3/org.phoenicis.javafx.components.library.control.LibraryFeaturePanel.lambda$createShortcut$0(LibraryFeaturePanel.java:165)
	at phoenicis.scripts@5.0-alpha-3/org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at phoenicis.scripts@5.0-alpha-3/org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Exception in thread "pool-4-thread-2" java.lang.ClassCastException: class java.lang.String cannot be cast to class org.graalvm.polyglot.Value (java.lang.String is in module java.base of loader 'bootstrap'; org.graalvm.polyglot.Value is in module org.graalvm.sdk of loader 'app')
	at phoenicis.javafx@5.0-alpha-3/org.phoenicis.javafx.components.library.control.LibraryFeaturePanel.lambda$createShortcut$0(LibraryFeaturePanel.java:165)
	at phoenicis.scripts@5.0-alpha-3/org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at phoenicis.scripts@5.0-alpha-3/org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by Razzeee** [comment]
also mentiond in: https://github.com/PhoenicisOrg/phoenicis/issues/2326#issuecomment-764464233

**Comment by plata** [comment]
The problem is: the container is used to figure out which engine (e.g. Wine) shall be used to run the shortcut.

To understand the use case: You have an executable which can run directly without being installed?

**Comment by Razzeee** [comment]
Yes, correct, I think I also linked to it (might have been the other issue)
One thing that I need to do now due to wine 6 being out and having
installed with 5.9 is choosing 5.9 on every install, otherwise it forgets
about the data.

**Comment by plata** [comment]
I'm thinking how this can fit best into Phoenicis' concept because normally everything should be in a container. The container defines the environment where the executable runs. This is e.g. the Wine version but also additional verbs and settings.

If we would enable running an executable without any container, you could never use verbs. I don't think we want that.

So I see two options:
1. Run executable outside a container but with a given container.
2. Have a simple "installer" which only copies/moves the executable into a container.

**Comment by Razzeee** [comment]
By the way, as I mentioned in one of the other tickets, I'm currently installing my .exe (not a setup) each day, so that I can run it (as it runs the setup).
Isn't that basically what we want, just that we need a shortcut (or whatever we call this) to remember the first run choices. (and maybe make them configurable at some point)

I'm also wondering where the files end up at the moment, the .exe (run from Downloads) seems to have created two folders in the download folder. But trying to migrate my whole setup into the container including these files doesn't show my data, so I'm guessing there are more files. (totally understand if you don't know)

**Comment by plata** [comment]
Have you tried using the custom installer (apps tab) to run the executable or to write an `OnlineInstallerScript`?

**Comment by Razzeee** [comment]
I'm only able to use the custom installer haven't found another way to
install/use it. That's what I have to do every day to just get the exe to
run.

Haven't looked at a custom script yet.

**Comment by plata** [comment]
Take a look at this script as an [example](https://github.com/PhoenicisOrg/scripts/blob/master/Applications/Graphics/Photofiltre/Online/script.js). Should be straight forward.

**Comment by Razzeee** [comment]
Looks simple enough, but I can't find a way to just run a script. So I would need to send it upstream or add my own repo in settings?

**Comment by plata** [comment]
We have a [README](https://github.com/PhoenicisOrg/scripts). You're welcome to provide the script for everybody if it works.

**Comment by Razzeee** [comment]
Did that, but left out the miniature, hangs forever when installing, here's the log:

```
[klampe@nbssc150os ~]$ flatpak run org.phoenicis.playonlinux 
Gtk-Message: 19:37:07.079: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:37:07.079: Failed to load module "pk-gtk-module"
Gtk-Message: 19:37:07.079: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:37:07.079: Failed to load module "pk-gtk-module"
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
[INFO ] org.phoenicis.repository.DefaultRepositoryManager (l.133) - Adding repositories: [org.phoenicis.repository.location.GitRepositoryLocation@5ce1c68[https://github.com/Razzeee/scripts,add-mobilepass], org.phoenicis.repository.location.GitRepositoryLocation@476c8784[https://github.com/PhoenicisOrg/scripts,release/5.0-alpha-3], org.phoenicis.repository.location.ClasspathRepositoryLocation@1d19bd3e[/org/phoenicis/repository]] at index 0
Jan 30, 2021 7:37:11 PM com.sun.javafx.css.StyleManager$ImageCache getCachedImage
WARNING: Error loading image: file:/home/klampe/.Phoenicis/shortcuts/MobilePass.miniature
Jan 30, 2021 7:37:13 PM com.sun.javafx.css.StyleManager$ImageCache getCachedImage
WARNING: Error loading image: file:/home/klampe/.Phoenicis/shortcuts/MobilePass.miniature
[INFO ] org.phoenicis.repository.types.MultipleRepository (l.46) - Fetching applications for: org.phoenicis.repository.types.MultipleRepository@db726ca[repositories=[GitRepository(url: 'https://github.com/Razzeee/scripts', folder: '/home/klampe/.Phoenicis/cache/git1643601134', branch: 'add-mobilepass'), GitRepository(url: 'https://github.com/PhoenicisOrg/scripts', folder: '/home/klampe/.Phoenicis/cache/git-298283779', branch: 'release/5.0-alpha-3'), org.phoenicis.repository.types.ClasspathRepository@370d90c[packagePath=/org/phoenicis/repository]]]
[INFO ] org.phoenicis.repository.types.GitRepository (l.72) - Begin fetching process of 'https://github.com/PhoenicisOrg/scripts' to '/home/klampe/.Phoenicis/cache/git-298283779'
[INFO ] org.phoenicis.repository.types.GitRepository (l.135) - Opening git-repository at '/home/klampe/.Phoenicis/cache/git-298283779'
Jan 30, 2021 7:37:16 PM com.sun.javafx.css.StyleManager$ImageCache getCachedImage
WARNING: Error loading image: file:/home/klampe/.Phoenicis/shortcuts/MobilePass.miniature
[INFO ] org.phoenicis.repository.types.GitRepository (l.141) - Pulling new commits to '/home/klampe/.Phoenicis/cache/git-298283779'
[INFO ] org.phoenicis.repository.types.GitRepository (l.145) - Finished pulling new commits to '/home/klampe/.Phoenicis/cache/git-298283779'
[INFO ] org.phoenicis.repository.types.GitRepository (l.72) - Begin fetching process of 'https://github.com/Razzeee/scripts' to '/home/klampe/.Phoenicis/cache/git1643601134'
[INFO ] org.phoenicis.repository.types.GitRepository (l.135) - Opening git-repository at '/home/klampe/.Phoenicis/cache/git1643601134'
[INFO ] org.phoenicis.repository.types.LocalRepository (l.77) - Reading directory : /home/klampe/.Phoenicis/cache/git-298283779
[INFO ] org.phoenicis.repository.types.GitRepository (l.141) - Pulling new commits to '/home/klampe/.Phoenicis/cache/git1643601134'
[INFO ] org.phoenicis.repository.types.GitRepository (l.145) - Finished pulling new commits to '/home/klampe/.Phoenicis/cache/git1643601134'
[INFO ] org.phoenicis.repository.types.LocalRepository (l.77) - Reading directory : /home/klampe/.Phoenicis/cache/git1643601134
[Use -Dgraal.LogFile=<path> to redirect Graal log output to a file.]
Cannot install GraalVM MBean due to Receiver class org.graalvm.compiler.hotspot.management.HotSpotGraalManagement does not define or inherit an implementation of the resolved method 'abstract void initialize(org.graalvm.compiler.hotspot.HotSpotGraalRuntime, org.graalvm.compiler.hotspot.GraalHotSpotVMConfig)' of interface org.graalvm.compiler.hotspot.HotSpotGraalManagementRegistration.
Jan 30, 2021 7:37:21 PM com.sun.javafx.css.StyleManager$ImageCache getCachedImage
WARNING: Error loading image: file:/home/klampe/.Phoenicis/shortcuts/MobilePass.miniature
Jan 30, 2021 7:37:23 PM com.sun.javafx.css.StyleManager$ImageCache getCachedImage
WARNING: Error loading image: file:/home/klampe/.Phoenicis/shortcuts/MobilePass.miniature
[WARN ] org.phoenicis.javafx.views.mainwindow.installations.dto.InstallationDTO (l.56) - Installation ID (SafeNet MobilePASS_1612031850628) contains invalid characters, will remove them.
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - Unable to create temporary file, phoenicis2534296686935199040.com/filesSN/Index/79cca6a24fcc41c48a6dc31162a9ee7e?sid=6aded7501b842c50f12064606e4bcbaf
	at java.base/java.io.File$TempDirectory.generateFile(File.java:1986)
	at java.base/java.io.File.createTempFile(File.java:2078)
	at phoenicis.tools@5.0-alpha-3/org.phoenicis.tools.files.FileUtilities.createTmpFile(FileUtilities.java:270)
	at <js> createTempFile(Unnamed:137:2980-3017)
	at <js> _installationCommand(Unnamed:39:1158-1182)
	at <js> go(Unnamed:29:1044-1081)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.ObjectProxyHandler.invoke(HostInteropReflect.java:694)
	at com.sun.proxy.$Proxy64.go(Unknown Source)
	at phoenicis.javafx@5.0-alpha-3/org.phoenicis.javafx.components.application.skin.ApplicationInformationPanelSkin.lambda$installScript$7(ApplicationInformationPanelSkin.java:271)
	at phoenicis.scripts@5.0-alpha-3/org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at phoenicis.scripts@5.0-alpha-3/org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by host exception: java.io.IOException: Unable to create temporary file, phoenicis2534296686935199040.com/filesSN/Index/79cca6a24fcc41c48a6dc31162a9ee7e?sid=6aded7501b842c50f12064606e4bcbaf

Exception in thread "pool-4-thread-2" Unable to create temporary file, phoenicis2534296686935199040.com/filesSN/Index/79cca6a24fcc41c48a6dc31162a9ee7e?sid=6aded7501b842c50f12064606e4bcbaf
	at java.base/java.io.File$TempDirectory.generateFile(File.java:1986)
	at java.base/java.io.File.createTempFile(File.java:2078)
	at phoenicis.tools@5.0-alpha-3/org.phoenicis.tools.files.FileUtilities.createTmpFile(FileUtilities.java:270)
	at <js> createTempFile(Unnamed:137:2980-3017)
	at <js> _installationCommand(Unnamed:39:1158-1182)
	at <js> go(Unnamed:29:1044-1081)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.ObjectProxyHandler.invoke(HostInteropReflect.java:694)
	at com.sun.proxy.$Proxy64.go(Unknown Source)
	at phoenicis.javafx@5.0-alpha-3/org.phoenicis.javafx.components.application.skin.ApplicationInformationPanelSkin.lambda$installScript$7(ApplicationInformationPanelSkin.java:271)
	at phoenicis.scripts@5.0-alpha-3/org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at phoenicis.scripts@5.0-alpha-3/org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by host exception: java.io.IOException: Unable to create temporary file, phoenicis2534296686935199040.com/filesSN/Index/79cca6a24fcc41c48a6dc31162a9ee7e?sid=6aded7501b842c50f12064606e4bcbaf


```

**Comment by plata** [comment]
It complains about the miniature:
```
WARNING: Error loading image: file:/home/klampe/.Phoenicis/shortcuts/MobilePass.miniature
```
For starters, you can just copy+paste one from another app.

**Comment by Razzeee** [comment]
It does, but even with one, it runs into the same exception

**Comment by plata** [comment]
Could you create a pull request with what you did? Kinda hard to tell like this.

**Comment by Razzeee** [comment]
Done, you can find it at https://github.com/PhoenicisOrg/scripts/pull/1231
