### ISSUE TITLE
PlayOnMac 4 Wine Versions

### ISSUE THREAD

**Issue by thekee04** [PhoenicisOrg/phoenicis#2458]
I saw a post somewhere on wine versions not showing for phoenicis and wondered if there was a fix for play on mac 4 too
<img width="745" alt="Screenshot 2021-11-11 at 17 35 27" src="https://user-images.githubusercontent.com/83502726/141343478-c2af3e72-12b4-4ff4-8306-911ab6878009.png">

*Latest play on mac version
*Mac Big Sur

**Comment by Nrezinorn** [comment]
System Version:	macOS 12.0.1 (21A559)
  Kernel Version:	Darwin 21.1.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Computer Name:	Jim’s MacBook Pro
  User Name:	Jim (nrezinorn)
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	23:04

It looks like an issue with the underlying Python SSL Libraries

`% ./playonmac
[main] Message: PlayOnMac (4.4.3) is starting
[clean_tmp] Message: Cleaning temp directory
[install_plugins] Message: Checking plugin: ScreenCap...
[update_check] Message: List is up to date
Donwloading https://phoenicis.playonlinux.com/index.php/wine?os=darwin
Traceback (most recent call last):
  File "urllib/request.pyc", line 1350, in do_open
  File "http/client.pyc", line 1240, in request
  File "http/client.pyc", line 1286, in _send_request
  File "http/client.pyc", line 1235, in endheaders
  File "http/client.pyc", line 1006, in _send_output
  File "http/client.pyc", line 946, in send
  File "http/client.pyc", line 1409, in connect
  File "ssl.pyc", line 500, in wrap_socket
  File "ssl.pyc", line 1040, in _create
  File "ssl.pyc", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/PlayOnMac.app/Contents/Resources/playonlinux/python/wine_versions/WineVersionsFetcher.py", line 24, in _sync_fetch_all_available_wine_versions
  File "urllib/request.pyc", line 222, in urlopen
  File "urllib/request.pyc", line 525, in open
  File "urllib/request.pyc", line 542, in _open
  File "urllib/request.pyc", line 502, in _call_chain
  File "urllib/request.pyc", line 1393, in https_open
  File "urllib/request.pyc", line 1353, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>`

Valid Chain as of Nov 26 2021:
`Certificate chain
 0 s:/CN=phoenicis.org
   i:/C=US/O=Let's Encrypt/CN=R3
 1 s:/C=US/O=Let's Encrypt/CN=R3
   i:/C=US/O=Internet Security Research Group/CN=ISRG Root X1
 2 s:/C=US/O=Internet Security Research Group/CN=ISRG Root X1
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3`
   
Adding additional certs to bundle doesn't fix as the R3 (letsencryptauthorityx3.pem) and ISRG X1 (isrgrootx1.pem) roots are already in the file):
/Applications/PlayOnMac.app/Contents/Resources/lib/python3.8/certifi/cacert.pem

**Comment by Nrezinorn** [comment]
@qparis 

Got a functional Workaround:
Added a variable for MacOS that sets the path to ca_file and then modified WineVersionsFetcher.py line 24, to actually verify certificate validity:

`            handle = urllib.request.urlopen(request, cafile=Variables.ca_file, timeout=5)`

The full solution requires some extra work, as simply adding this fix will break non Mac downloads.

**Comment by Nrezinorn** [comment]
The proposed fix is in https://github.com/PlayOnLinux/POL-POM-4/pull/69
